### ISSUE TITLE
Support setproperty as well to modify columns in place

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#11]
In the same way as Tables implements `getproperty` for a "lazy row" of a `NamedTuple` of vectors [here](https://github.com/JuliaData/Tables.jl/blob/master/src/Tables.jl#L118), I wonder whether it should also implement `setproperty!`. This is a nice bonus of using a lazy row rather than a `NamedTuple` for iteration: we can get DataFramesMeta's `@byrow!` for free. For example:

```julia
foreach(rows(df)) do row
  row[:c] = row[:a] + row[:b]
end
```

**Comment by quinnj** [comment]
Certainly something worth considering; it would definitely have to be optional, since a number of sources couldn't support this (CSV row-iterator, SQLite table row-iterator, etc.), but for those that could, it would certainly be handy.

**Comment by quinnj** [comment]
I don't think there's anything Tables.jl-specific here; if a custom Row type wants to support setproperty!, then there's nothing stopping them from doing so and documenting that it works. It isn't something the Tables.jl interface needs (or wants) to enforce though (NamedTuples already couldnt' support this).

**Comment by piever** [comment]
Maybe one thing that could be done on the Tables side is to add a `setproperty!` method to the default fallback for row iteration of a `columnstable` (where each row is a `ColumnsRow`). Say:

```julia
function Base.setproperty!(c::ColumnsRow, nm::Symbol, x)
    getproperty(getfield(c, 1), nm)[getfield(c, 2)] = x
end
```

In this way it would be clear that all column based storage can have a `setproperty!` method on rows (and they would, by default, if they don't implement a "non-fallback" row access).

**Comment by quinnj** [comment]
With #131 merged, I'd like to commit to a simple, generic Tables.jl interface that is mainly about table transfer and consumption. I've proposed in [another issue](https://github.com/JuliaData/Tables.jl/issues/116#issuecomment-583702119) that it seems to make sense to get together and define a stricter interface that would support in-place and mutating operations.
