### ISSUE TITLE
Additional Walkthroughs of making a Table type

### ISSUE THREAD

**Issue by kescobo** [JuliaData/Tables.jl#114]
Would be great to have more walkthroughs of the steps to turning a type into a `Table`.

Example: https://github.com/JuliaData/Tables.jl/wiki/MySQL.jl

**Comment by quinnj** [comment]
We now have official docs w/ [a section](https://juliadata.github.io/Tables.jl/dev/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)-1) specifically walking through implementing the Tables.jl interface.

**Comment by kescobo** [comment]
That looks excellent, thanks! 👍
