### ISSUE TITLE
Documentation on "How to test Table type"

### ISSUE THREAD

**Issue by kescobo** [JuliaData/Tables.jl#115]
Add some documentation to the README on testing a `Table` type.

**Comment by quinnj** [comment]
Ok, I added another doc section walking through some ideas for how to test a table type in the official docs (in https://github.com/JuliaData/Tables.jl/commit/35e8994b7f5424636128c8774a107e1300fa5ba3). We could certainly provide something more automated in a TablesTests.jl package eventually, but for now, I think it's decently straightfoward to just test things yourself w/ a little roundtripping.

**Comment by kescobo** [comment]
👍
