### ISSUE TITLE
collect only some columns

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#12]
I'm not entirely sure whether I'm missing it or it is not implemented, but I think we also need some `columns(source, names)` to only collect some columns. It's particularly relevant because some sources may implement optimized methods for it (for example some SQL dataset may query only some columns).

**Comment by quinnj** [comment]
Yeah, it's a bit unfortunate that `Tables.buildcolumns`, as an implementation detail, builds the columns eagerly and thus seems to require something like this (in the normal case of say, a DataFrame, you would just select the columns you wanted anyway after calling `Tables.columns(x)`).

As I thought about this, my concern was where do we stop in terms of supporting these kinds of "transforms" while building up columns in the generic fallback.

The solution I've come to is to simply define something like:
```julia
struct Select{T, names}
    source::T
end

function select(x::T, names::Symbol...) where {T}
    r = Tables.columnaccess(T) ? Tables.columns(x) : Tables.rows(x)
    return Select{typeof(r), names}(r)
end

Tables.istable(::Type{<:Select}) = true

Base.@pure function typesubset(::Tables.Schema{names, types}, nms) where {names, types}
    return Tuple{Any[Tables.columntype(names, types, nm) for nm in nms]...}
end

function Tables.schema(s::Select{T, names}) where {T, names}
    sch = Tables.schema(s.source)
    sch === nothing && return nothing
    return Tables.Schema(names, typesubset(sch, names))
end

# Tables.columns: make Select property-accessible
Base.getproperty(s::Select, nm::Symbol) = getproperty(getfield(s, 1), nm)
Base.propertynames(s::Select{T, names}) where {T, names} = names
Tables.columnaccess(::Type{<:Select}) = true
Tables.columns(s::Select) = s

# Tables.rows: implement Iterator interface
Base.IteratorSize(::Type{Select{T, names}}) where {T, names} = Base.IteratorSize(T)
Base.length(s::Select) = length(s.source)
Base.IteratorEltype(::Type{Select{T, names}}) where {T, names} = Base.IteratorEltype(T)
Base.eltype(s::Select{T, names}) where {T, names} = SelectRow{eltype(s.source), names}
Tables.rowaccess(::Type{<:Select}) = true
Tables.rows(s::Select) = s

# we need to iterate a "row view" in case the underlying source has unknown schema
# to ensure each iterated row only has `names` propertynames
struct SelectRow{T, names}
    row::T
end

Base.getproperty(row::SelectRow, ::Type{T}, col::Int, nm::Symbol) where {T} = getproperty(getfield(row, 1), T, col, nm)
Base.getproperty(row::SelectRow, nm::Symbol) = getproperty(getfield(row, 1), nm)
Base.propertynames(row::SelectRow{T, names}) where {T, names} = names

function Base.iterate(s::Select{T, names}, st=()) where {T, names}
    state = iterate(s.source, st...)
    state === nothing && return nothing
    row, st = state
    return SelectRow{typeof(row), names}(row), (st,)
end
```

I've been playing around w/ a few "transform" implementations like this, mainly as an exercise to stress-test the Tables.jl interface, but it's pretty great how well they layer on to the underlying Tables.jl interface functions and provide easy, inference-free transforms.

I've just been collecting some of these locally, but I'd be happy to push them to a repo if we want to actually seriously consider them (I haven't at this point other than, like I mentioned, stress-test the Tables.jl interface).

**Comment by piever** [comment]
This is a larger question, but I feel that currently in the various tables ecosystems there is an awful lot of code duplication and at least in terms of implementation of the basic algorithms, we could provide some unification here. Can we start playing around with a TableTools repository and see how far that goes?

In particular all the Query style operators could live there happily.
```julia
map_rows(f, df) = (f(row) for row in rows(df))
filter_rows(f, df) = (row for row in rows(df) if f(row))
```
and things like that.

Then one would just need to:
```julia
map(f, df::DataFrame) = DataFrame(map_rows(f, df)))
```
and things like that to gain a lot of functionality with very little code.

Similarly for column selection (esp. since JuliaDB already has a few special column selectors to simplify usage, see [here](https://juliadb.org/latest/api/selection.html#Column-special-selection-1)).

Personally I would love a design like Plots where the key definitions to overload are in Tables, there is a bunch of functionality implemented using only those definitions and backend can overload this implementations whenever they can offer a more performant version.

**Comment by quinnj** [comment]
I started this repo for collecting some of the test implementations: https://github.com/JuliaData/TableOperations.jl/blob/master/src/TableOperations.jl. They are by no means production code or even ever meant to be, but it can be a place to try things out. The `Transforms` is something I've been working to allow CSV.jl + others to detangle themselves from DataStreams and not break backwards compatibility.

It'd be interesting to sync w/ @davidanthoff and the QueryOperators.jl implementations; I'm not sure on where the implementations would diverge, but it'd be interesting to play around w/ things.

I'll throw out the caveat that I'm not too interested/have the time to really put efforts in a TableOperations.jl kind of package; I don't use those kind of general transforms very much or necessarily have the experience implementing them; creating the TableOperations.jl package was purely an exercise in throwing some quick examples together to see how the Tables.jl interfaces would play out.

**Comment by piever** [comment]
I was thinking that either @davidanthoff implementations in Queryoperators (which AFAIU mainly rely on iterating `NamedTuples`) or maybe the Query operators in DataStreams could be ported to work directly on Tables, be put in a low dependency package and other tabular data packages could default to them unless there is an implementation that's more efficient for that given tabular format.

I'm actually quite interested in this project as I've done some of this already in IndexedTables.

**Comment by quinnj** [comment]
I think QueryOperators would be a great place since it already has a nice layout/framework for this kind of stuff; but I'm not sure if it would really work since it lives one level higher in the interface hierarchy: you can do QueryOperators on any iterable, not just a table. It's not clear if there would be interface clashes if QueryOperators started assuming that everything was property-accessible iterators (my hunch is that it would work, but I'm really not sure).

**Comment by quinnj** [comment]
I am very interested in getting this functionality for a few specific use-cases, particularly the `select` case, since that's been a long-requested CSV.jl feature (only parsing certain columns), and the new internal design of CSV.jl + Tables.jl makes it very cheap & easy.

**Comment by quinnj** [comment]
This feature has been requested for long enough, so I'm putting in the simple `select` code (with tests) in this PR: https://github.com/JuliaData/Tables.jl/pull/62. That way we can have it and people can use it and we can maybe figure out a more cohesive story/package later for all sorts of fancy table operations.

**Comment by piever** [comment]
If this is already in TableOperations, shouldn't we just like TableOperations in the README? In my mind that is a nice design already: the basic interface lives here, table operations live in TablesOperations (and potentially in the future DataFramesMeta-like macros could live in TablesMeta). Is the concern that CSV.jl would rather not depend on TablesOperations?

**Comment by quinnj** [comment]
For now, we only have `transform` and `select` operations, so it didn't seem quite enough to justify creating the TablesOperations.jl package yet (people would probably be disappointed to see things like map/filter/group/join aren't supported). I also rather like the user api of doing `Tables.transform` and `Tables.select` vs. TableOperations. Anyway, we now provide `Tables.select` in the latest release, which allows specifying a few columns to "subset" from any Tables.jl source.
