### ISSUE TITLE
Case of LazyArrays and Tables.materializer

### ISSUE THREAD

**Issue by tlienart** [JuliaData/Tables.jl#122]
I ran into a fairly sneaky issue with [`ScientificTypes`](https://github.com/alan-turing-institute/ScientificTypes.jl) which uses `Tables` as a backend, the story is a bit long but to  cut it short:

* CSV.jl uses threading when it can and generates dataframes with `LazyArrays.ApplyArray`
* When using `RDatasets` and loading data from it  and - say - using Juno which automatically sets threading  if it sees  multiple core, you will  get dataframes with lazyarrays,
* a key operation in  ScientificTypes is to coerce Tables to  get a copy of the table where columns have been coerced to a given target type
* that key operation happens here https://github.com/alan-turing-institute/ScientificTypes.jl/blob/fe7e10518970a7d969cbe9c156effa126c2843a6/src/tables.jl#L68-L76
*  the key line in there is `Tables.materializer(X)(coltable)`

Effectively what seems to  happen  is that if the `coltable` has `LazyArrays` in there, I'm guessing the materializer falls back on something like  a copy of the initial  `X` or something of the sorts. 

I'm not exactly sure what's a  proper way around this, it seems that to materialize a `LazyArray`  there's this `materialize` function which would potentially do what I want but that would add to the  deps of Tables which is supposed to be barebones.

Any suggestions? (PS: here's the original discussion where it took me some time to work out what the  problem was https://github.com/alan-turing-institute/ScientificTypes.jl/issues/49 )

**Comment by nalimilan** [comment]
If `X` is a `DataFrame`, then yes, `Tables.materializer(X)(coltable)` is going to call `copy` on columns since it's equivalent to `DataFrame(coltable)`, i.e. `DataFrame(coltable, copycols=true)`.

Maybe we could allow `Tables.materializer(X, copycols=false)(coltable)`, or  `Tables.materializer(X)(coltable, copycols=false)`. But that would require all packages implementing the Tables.jl interface do support that argument. At least, the former wouldn't require them to also have their constructor support it (and they could just ignore it).

**Comment by tlienart** [comment]
Hmm there may be a misunderstanding here but granted that's my fault from not explaining the problem properly.

The flow of operations in ST is like this:

Data -> Coercion -> New data

where New data contains a mix of the original columns and some columns that will  go through a `convert` operation. 

This works fine in the standard setting  where DataFrames are backed  by standard arrays. 

However, when using CSV + threading, you get a DataFrame backed by LazyArrays. These do not materialize in the same way and what is happening is instead:

Data -> Coercion -> Data

Where data is **unchanged**. That's why I said that  I think there's a fallback in materialize to just copy stuff over.

### What we do at the moment

* we check whether the data structure of the column is a LazyArrays.ApplyArray explicitly
* if it is, we convert  it to a "standard" array before doing the actual type conversion

this works but is effectively a hack because I don't want to load LazyArrays as a dependency so I have to go via a roundabout way to check whether the type of  the object is something that looks like `LazyArrays.ApplyArray`.

Effectively what  I'm poiting out is that the `materialize` function from Tables  behaves somewhat unexpectedly  on a lazyarray.applyarray.

**Comment by nalimilan** [comment]
Mmm, so you mean that `Tables.materializer(X)(coltable)` doesn't use the columns from `coltable`, but the original columns from `X`? Or that calling `coerce` on columns has no effect? Maybe it's just that this condition returns `false` for some reason?
https://github.com/alan-turing-institute/ScientificTypes.jl/blob/fe7e10518970a7d969cbe9c156effa126c2843a6/src/tables.jl#L38

Also, could you post a reproducer?

**Comment by tlienart** [comment]
```julia
using CSV, ScientificTypes, RDatasets, Tables

Threads.nthreads() # 2

df = dataset("MASS", "Boston")
df = select(df, [:Chas, :Crim])

typeof(df.Chas) # LazyArrays.ApplyArray

cc = coerce(df.Chas, Continuous)

eltype(cc) # Float64

scitype(cc) # AbstractArray{Continuous, 1}

# ============

function _coerce_col(Xcol, name, types; args...)
    col = getproperty(Xcol, name)
    if haskey(types, name)
        return coerce(col, types[name]; args...)
    else
        return col
    end
end

function coerce2(X, pairs::Pair{Symbol}...; verbosity=1)
    names = Tables.schema(X).names
    Xcol  = Tables.columntable(X)
    coltable = NamedTuple{names}(_coerce_col(Xcol, name, Dict(pairs);
                                             verbosity=verbosity)
                                 for name in names)

    @show eltype(coltable.Chas) # Float64

    return Tables.materializer(X)(coltable)
end

dfc = coerce2(df, :Chas=>Continuous)

eltype(dfc.Chas) # Int64 still
```

So the part that matters here is  the `show`, everything up to there  works fine since  `coltable.Chas` has the element type we want (float), but then the materializer screws up.

Note that  if you do exactly the same thing but with  1 thread, it will work fine because CSV called by RDatasets will be non-threaded and so will not use LazyArrays

This is why I think there's something fishy  going on with `materializer` + `lazyarrays`, likely something to  do with the fact that `lazyarrays`  need to be materialized themselves or something along those lines.

**Comment by nalimilan** [comment]
Thanks. It doesn't look like Tables.jl is involved at all: just doing `copy(cc)` reproduces the problem.

AFAICT, the bug is that `copy(A::ApplyArray) = ApplyArray(A.f, map(copy,A.args)...)` when it should be `copy(A::ApplyArray{T,N}) where {T,N} = ApplyArray{T,N}(A.f, map(copy,A.args)...)`. There may be other places with the same problem.

**Comment by tlienart** [comment]
closing here and opening an issue there https://github.com/JuliaArrays/LazyArrays.jl/issues/85 thanks @nalimilan for your  help, I quoted your suggestion in the other issue
