### ISSUE TITLE
add `nrow` and `ncol`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/Tables.jl#124]

**Comment by joshday** [comment]
I don't see a benefit to having this in Tables at the cost of adding more methods to the interface.

**Comment by pdeffebach** [comment]
Is the canonical recommendation to do this `nrow = length(Tables.rows(t))` and `ncol = length(Tables.columns(t))`? if `t = Tables.columns(df)`?

**Comment by xiaodaigh** [comment]
> length(Tables.rows(t))

Works because many iterators has the has length traits

**Comment by joshday** [comment]
To expand, "most" tables in practice have a length, but the Tables interface doesn't guarantee it.  This is what I would do to get `nrows` and `ncols` from column/row iterators:

```julia
t = Tables.columns(df)

nrows = length(first(t))

ncols = length(t) 
```

```julia
t2 = Tables.rows(df)

nrows = length(t2)

ncols = length(first(t2))
```

**Comment by pdeffebach** [comment]
Thanks for the note. 

Just to be clear, the iteration itself is determined by `DataFrames` (for example), so `length` may not be guaranteed either. 

I was under the impression iteration was implemented by `Tables.jl` via some sort of 

```
getproperty(t, s) for s in propertynames(t)
```

**Comment by pdeffebach** [comment]
Also your second example doesn't work for generic tables because iteration on rows isn't defined, even as a fallback. Ref #75

**Comment by joshday** [comment]
> Just to be clear, the iteration itself is determined by DataFrames (for example), so length may not be guaranteed either.

Correct.  A DataFrame probably has `length` defined, but other things may not.  Tables doesn't need the `length` method in order to function, but most things probably have a `length`.

> iteration on rows isn't defined

Iteration over *a single row* isn't guaranteed, but `rows(t)` returns an iterator.  In both my examples, there's no guarantee that any of those `length` methods exist, but in practice they probably do.

**Comment by xiaodaigh** [comment]
https://docs.julialang.org/en/v1/manual/interfaces/

There is an IteratorSize() type checker and the default is `HasLength()` trait. Mostly, likely `rows` would return an iterator that has length

**Comment by ablaom** [comment]
You can get the number of columns from `length(Tables.schema(X).names)`:

```julia
julia> using Tables

julia> X = (x1=rand(3), x2=rand(3)) 
(x1 = [0.893945, 0.696079, 0.544089],
 x2 = [0.162807, 0.0328988, 0.567906],)

julia> length(Tables.schema(X).names)
2
```

**Comment by quinnj** [comment]
I think there have been enough clarifications and suggestions here; but yeah, I dont' think we need anything in the interface for this.
