### ISSUE TITLE
Implement trait types?

### ISSUE THREAD

**Issue by tk3369** [JuliaData/Tables.jl#129]
Is there any benefit to implement trait types that we can use for dispatch? e.g.

```julia
abstract type TableStyle end
abstract type IsTable <: TableStyle end

struct RowTable <: IsTable end
struct ColumnTable <: IsTable end

struct NotTable <: TableStyle end

TableStyle(::Type) = NotTable()
TableStyle(::Type{<:AbstractDataFrame}) = ColumnTable()
```

**Comment by quinnj** [comment]
No. In the very earliest iterations of Tables.jl, this was considered, but there are table types that can be row _OR_ column oriented (i.e DataFrames). That is, DataFrames has the power to provide its own column _AND_ row access functions, which match its goals/design.

Also note that `Tables.istable` and `Tables.rowaccess` are type stable and inferrable at compile time (for most table types).

What benefits do you imagine?

**Comment by tk3369** [comment]
I'm just thinking about this.  From a user perspective, maybe I would want to choose to use either row or column-interface depending on the object's current layout (thus avoiding an unnecessary conversion)?

```julia
action(x) = action(TableStyle(x), x)
action(::IsTable, x) = "do something useful with table"
action(::NotTable, x) = error("are you crazy?")
action(::ColumnTable, x) = "use column-interface functions for best performance"
action(::RowTable, x) = "use row-interface functions for best performance"
```
