### ISSUE TITLE
Adding interface to Tables.jl

### ISSUE THREAD

**Issue by cormullion** [JuliaData/Tables.jl#148]
Hi Jacob! You said "don't hesitate to open a new issue, even just for a question" so... 

I added a basic Table type to Luxor.jl ages ago (https://github.com/JuliaGraphics/Luxor.jl/blob/master/src/Table.jl) but I feel guilty now that `Tables.jl` is becoming quite valuable in the ecosystem, so I'm wondering whether I should rewrite my code or just rename things to avoid problems...

Basically for me a Table is just a list of center positions of 'cells'. The rows and columns can have various widths and heights. So you can place anything at a cell location because you know its centre and can get its dimensions. There's nothing stored in the cells, though... I just wanted to build all the arithmetic into it so I didn't have to keep track of them in code.

```julia
using Luxor
@draw begin
    for cell in Table(20:5:70, 20:5:70)
        randomhue()
        circle(first(cell), 10, :fill)
        sethue("white")
        text(string(last(cell)), first(cell), halign=:center, valign=:middle)
    end
end
```

<img width="396" alt="Screenshot 2020-02-12 at 09 47 32" src="https://user-images.githubusercontent.com/52289/74323080-d9962280-4d7c-11ea-9693-83cfb230859b.png">

Do you think this might easy to interface with Tables.jl or is it a bit too way out?

**Comment by quinnj** [comment]
Hey @cormullion! Sorry for the slow response here; I remember seeing your questions come up originally and then I got pulled in a few different ways on some database stuff; but I'm circling back around on Tables.jl issues.

> so I'm wondering whether I should rewrite my code or just rename things to avoid problems

No, there shouldn't be any problems/issues here. Tables.jl actually _doesn't_ define a `Table` type at all, just a bunch of table-related interface functions. It's also contextual: if I come across a `Table` type in Luxor.jl, I'd assume it's more related to something more geometric than a data-processing task.

> Do you think this might easy to interface with Tables.jl or is it a bit too way out?

Hmmm......I'm not sure I have a great answer here. The Tables.jl interfaces are about allowing various "square" (i.e. 2D rows and columns of cells with values in them) data formats to talk with each other through predictable access patterns. The main use I could see would be allowing some kind of ability to "save" a `Luxor.Table` in another format, like a DataFrame, csv file, or even as a Tables.jl-compatible JSON blob (via the JSONTables.jl package).

Anyway, sorry again for the slow response, but hopefully this helps a little?

**Comment by cormullion** [comment]
Thanks Jacob! I’ll watch from the sidelines for now 😂
