### ISSUE TITLE
Tables.matrix error?

### ISSUE THREAD

**Issue by tlienart** [JuliaData/Tables.jl#155]
This works:

```julia
T = (x=[1,2,3],y=[1,2,3])
Tables.matrix(T)
```

However this does not:

```julia
T = Tables.table(hcat([1,2,3],[1,2,3]))
M = Tables.matrix(T)
```

shouldn't it?

**Comment by tlienart** [comment]
This  line should be `.=`: https://github.com/JuliaData/Tables.jl/blob/42117f98ce6fd3efc6b8e62c76367a596f92ea29/src/matrix.jl#L73 I'll open a PR

**Comment by tlienart** [comment]
Hmm that's not the  only thing, 

```julia
T = Tables.table(hcat([1,2,3],[4,5,6]))
E = enumerate(Tables.Columns(T))
first(E)
```

returns  the first row (??)  :

```julia
julia> T = Tables.table(hcat([1,2,3],[4,5,6]))
Tables.MatrixTable{Array{Int64,2}}:
 :Column1  [1, 2, 3]
 :Column2  [4, 5, 6]

julia> E = enumerate(Tables.Columns(T))
Base.Iterators.Enumerate{Tables.MatrixTable{Array{Int64,2}}}(Tables.MatrixTable{Array{Int64,2}}:
 :Column1  [1, 2, 3]
 :Column2  [4, 5, 6])

julia> first(E)
(1, Tables.MatrixRow{Array{Int64,2}}:
 :Column1  1
 :Column2  4)
```

**Comment by tlienart** [comment]
@quinnj sorry to ping you on this, this is unfortunately causing dependency issues with MLJ which is quite tightly coupled with Tables but via packages which sometimes cannot explicitly depend on it (e.g. MLJModelInterface). Long story short, it would be great to get feedback on this issue, I'm happy to help out with a PR if that's useful but would first need a comment on whether things are indeed broken and what's the best path to fix them. 

Thanks a lot!

**Comment by quinnj** [comment]
Yeah, sorry for the delay here; I'm tied up today, but was planning on digging into this early tomorrow.

**Comment by quinnj** [comment]
Fix up: https://github.com/JuliaData/Tables.jl/pull/156
