### ISSUE TITLE
Example in docs throws an error

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaData/Tables.jl#165]
In the `AbstractMatrix` example for [implementing the tables interface](https://juliadata.github.io/Tables.jl/dev/#Testing-Tables.jl-Implementations-1), `mat = [1 4.0 "7"; 2 5.0 "8"; 3 6.0 "9"]` block throws a `invalid redefinition of constant mat` ERROR. 
Maybe a different variable name can fix this ERROR.

**Comment by quinnj** [comment]
I think this is just because you already have `mat` defined somehow; as a `const mat = ...` variable or a function from somewhere.

**Comment by Sov-trotter** [comment]
I ran the code in a new environment, still getting the same error. I think `mat` is defined in the definition of `MatrixTable`.
`mat(m::MatrixTable) = getfield(m, :matrix)`

**Comment by visr** [comment]
@Sov-trotter you're right, these two, both from the `MatrixTable` example, don't go well together.
```julia
mat(m::MatrixTable) = getfield(m, :matrix)
mat = [1 4.0 "7"; 2 5.0 "8"; 3 6.0 "9"]
```

Perhaps the `mat` function can just be renamed to `matrix`? @Sov-trotter, do you want to make a PR?

**Comment by Sov-trotter** [comment]
Yeah sure!. Also I just tested it out. Another way round would be simply renaming the `mat` variable in the example. @visr @quinnj  what would you suggest?

**Comment by visr** [comment]
I don't think it matters much either way. But since the `mat` function gets the `matrix` field, I suggested that. If Jacob disagrees, it's easy to update the PR.

**Comment by Sov-trotter** [comment]
Oh yeah right. I'll look into it. :)

**Comment by Sov-trotter** [comment]
#171
