### ISSUE TITLE
Paper to cite?

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#166]
Is there a paper/Zenodo link or similar for citing Tables.jl?

**Comment by ablaom** [comment]
(writing a design paper on MLJ)

**Comment by quinnj** [comment]
Not currently; I'm not familiar with what would be required to allow citing Tables.jl, but if someone does, I'm open to helping make it available.

**Comment by ablaom** [comment]
The simplest path (no review, no extra content) I know is to "publish" your software using Zenodo, which creates a DOI  (see, eg, the DOI banner at the top of [MLJ](https://github.com/alan-turing-institute/MLJ.jl)); quite a few julia packages seem to be doing that. If you plan to publish a peer-reviewed article, eg, Journal of Open Source Software (probably not the case for Tables.jl), then you may want to skip that to prevent diluting citations to the "real" thing.

**Comment by DilumAluthge** [comment]
Bump. Any update on a citation for Tables.jl?

**Comment by quinnj** [comment]
I looked at Zenodo once, but it didnt' seem entirely obvious what I was supposed to "do"

**Comment by digital-carver** [comment]
Zenodo doesn't seem to have any guide or even a clear UI path to it, but the process seems simple enough (disclaimer: I've not used Zenodo previously, just looked into it after seeing this issue): 

1. Login to Zenodo using Github OAuth
2. Go to https://zenodo.org/account/settings/github/
3. Flip the switch for this project to ON

After this, Zenodo should take care of generating DOIs every time a release is made. 

There's a [longer guide from Github here](https://guides.github.com/activities/citable-code/), describing the above process.

**Comment by quinnj** [comment]
Thank you @digital-carver! Here's a link to anyone interested: https://zenodo.org/record/4458977#.YA8Dc5DYrik. I'll also put it in the repo README for future posterity.
