### ISSUE TITLE
Should a matrix ever be a table? 

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#167]
I wonder if this behaviour is desirable:

**edited**

```julia
julia> using Tables

julia> Tables.istable(Matrix{Float64}(undef, 2, 3))
false

julia> Tables.istable(Matrix{Union{}}(undef, 2, 3))
true

```

Context: https://github.com/alan-turing-institute/MLJBase.jl/issues/239#issue-598619577

**Comment by quinnj** [comment]
Thanks for the report; fix is up: https://github.com/JuliaData/Tables.jl/pull/168
