### ISSUE TITLE
rowcount not working for row table 

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#170]
This doesn't seem right:

```julia
julia> using Tables
julia> X = Tables.table(rand(2,3));
julia> Xr = Tables.rowtable(X);

julia> Tables.rowcount(X) # hooray
2

julia> Tables.rowcount(Xr) # boo hoo
0

(junkk) pkg> st
    Status `~/.julia/environments/junkk/Project.toml`
  [bd369af6] Tables v1.0.4
```

**Comment by quinnj** [comment]
Please be careful using non-official/undocumented package internals! It was specifically decided to not export/support `rowcount` for 1.0 release. `Tables.rowcount` only works on the result of `Tables.columns`, which is the reason you're seeing issues here. I don't have plans to officially support this any time soon, so please take that into consideration in your APIs. Now, if you want to rely on `Tables.rowcount` for the result of `Tables.columns`, I've expressed elsewhere that I would consider that part of the API and not break it soon.

**Comment by ablaom** [comment]
No worries. I was not aware this was an internal method and will pass this onto our dev team.
