### ISSUE TITLE
Row(x::AbstractRow) = x

### ISSUE THREAD

**Issue by tkf** [JuliaData/Tables.jl#174]
I think this definition has some problems:

https://github.com/JuliaData/Tables.jl/blob/53dfc6c6d63f7f7aaee9ad4f4e52d447de057459/src/Tables.jl#L217

I think it's better to maintain the invariance `T(args..) isa T` if `T isa Type` [even though Julia documentation says it is OK to not do this "in _very rare_ cases"](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Constructors-that-don't-return-instances-of-their-own-type-1).

For example, due to this, `Tables.Row` interacts badly with `Base.Generator`:

```julia
julia> struct MyRow <: Tables.AbstractRow
           x
       end

julia> collect(Tables.Row(x) for x in [MyRow(1)]) |> typeof
Array{MyRow,1}

julia> collect(Tables.Row(x) for x in MyRow[]) |> typeof
Array{Tables.Row,1}
```

Notice that the element type of the last array is `Tables.Row` even though this generator cannot possibly produce a `Tables.Row`.

This is because [`Base.@default_eltype`](https://github.com/JuliaLang/julia/blob/9d70d450e771236b7e1e7cb0c7ac965a8843d662/base/array.jl#L647-L649) has a special case for `Base.Generator`.  It is better to fix this in `Base` but I think it is a good example that it is important to maintain `T(args..) isa T`.

I think it might be better to turn `Row` to an abstract type and soft-deprecate `AbstractRow`.  Something like

```julia
abstract type Row end
const AbstractRow = Row  # to be removed in 2.0

struct GenericRow{T} <: Row
    x::T
end

Row(x::Row) = x
Row(x) = GenericRow(x)
```

**Comment by nalimilan** [comment]
There are other `Abstract*` types in the package, so `AbstractRow` is more explicit than `Row`. How about making `AbstractRow` a kind of constructor instead?

**Comment by tkf** [comment]
I agree making `AbstractRow` callable is a valid option. I just thought it'd be better to make "consumer-facing" API (as opposed to implementer-facing) like `Row` to be a bit more terse.

There are only two more types with `Abstract` prefix:

* `AbstractColumns`: Similar soft-deprecation strategy is possible.
* `AbstractRowTable`: It's defined as `const AbstractRowTable = AbstractVector{T} where {T <: AbstractRow}` and it looks like just an internal type alias. So I don't think it counts as a "consistency penalty."

**Comment by quinnj** [comment]
I think my preference would be to take out the offending definition; I don't think it's the end of the world to have one more wrapping layer and will probably be optimized out anyway. That way we don't have to change the API at all.

**Comment by tkf** [comment]
Other than a possible performance penalty, it's a bit unsatisfactory that it's not possible to dispatch on the row type when it's wrapped.

If changing the type-hierarchy is not a good direction, adding a function `Tables.row` may be better?  If we use a function, it's nice that something like `Tables.row(x::NamedTuple) = x` is natural to do.

**Comment by quinnj** [comment]
Fix is up: https://github.com/JuliaData/Tables.jl/pull/255
