### ISSUE TITLE
Trying to make "getcolumn" work with JuliaDB

### ISSUE THREAD

**Issue by xinkai-zhou** [JuliaData/Tables.jl#175]
Hi, I'm having trouble making JuliaDB work with function "Tables.getcolumn()". Here is an example.

Create a small example.
```
using DataFrames, CSV, Tables, JuliaDB
df = DataFrame(A = 1:4, B = 5:8)
CSV.write("data/minimal-test.csv", df)
```

If I load the data as a dataframe then it would work.
```
dcsv = CSV.read("data/minimal-test.csv")
Tables.getcolumn(dcsv, :B)
```

But if I load it using JuliaDB, then it throws error: "ERROR: type IndexedTable has no field B".
```
dJDB = loadtable("data/minimal-test.csv")
Tables.getcolumn(dJDB, :B)
```

**Comment by quinnj** [comment]
Ah, looking into this I realize I misled you; there are no bugs here, but I didn't quite explain/follow the interface correctly. `Tables.getcolumn` is defined on the _result_ of `Tables.columns(x)`, not necessarily on `x` itself. DataFrames happens to define `getcolumn` directly on the DataFrame itself, but for JuliaDB/IndexedTables, you have to call `Tables.columns(dJDB)` first and then you can call `getcolumn` on the result. Sorry for the confusion!

**Comment by xinkai-zhou** [comment]
I see.. Thank you!
