### ISSUE TITLE
Equivalent of MATLAB Table function

### ISSUE THREAD

**Issue by sahindru** [JuliaData/Tables.jl#179]
Hi,
I am new to Julia (migrating from MATLAB). I intend to use MATLAB's TABLE(a,b,c) function in JULIA.  This function  tabulates data contained in vector a,b,c in the order specified.  May I request if there is an equivalent of this in JULIA. An example or two would help.
Your kind help is most welcome.

Thanks,
Avi

**Comment by quinnj** [comment]
I'm not entirely familiar with Matlab TABLE function, but are you looking for https://github.com/nalimilan/FreqTables.jl functionality? cc: @nalimilan

**Comment by nalimilan** [comment]
Yes, sounds like it.
