### ISSUE TITLE
[Feature request] Add Tables.nrows and Tables.ncols to the API

### ISSUE THREAD

**Issue by juliohm** [JuliaData/Tables.jl#181]
Can we have the following as part of the API?

```julia
Tables.nrows(table) = length(Tables.rows(table))
Tables.ncols(table) = length(Tables.columns(table))
```

Is there a better way to access these two already?

**Comment by Moelf** [comment]
why was this closed? I think this is a reasonable interface requirement. infinite columns and infinite rows are absolute minority

**Comment by bkamins** [comment]
There is `DataAPI.nrow` and `DataAPI.ncol` for this. (note a slight difference in name)

**Comment by Moelf** [comment]
DataAPI is not table interface
