### ISSUE TITLE
Add a Tables.partitions API interface

### ISSUE THREAD

**Issue by quinnj** [JuliaData/Tables.jl#185]
Some table sources have or are able to provide a natural partitioning of rows or columns. Some sinks desire to operate on partitions. It could be really useful/efficient to define a `Tables.partitions` function that allowed sources to produce an iterator of rows or columns, and that allowed sinks to operate on these partitions naturally (without needing to fully materialize things in between).

Things I'm still thinking about here:
* how do sinks specify that they want `Tables.rows` or `Tables.columns` for each partition? Or does the sink need to call `Tables.rows` or `Tables.columns` on each "partition"?
* Do we, and if yes then how do we enforce schema consistency across partitions?
* Do sinks need to know the # of partitions upfront, or are unknown length iterators fine?

Packages I'm aware of that could leverage partitioning:
* JuliaDB.jl: obvious, wants to partition table chunks across nodes
* Arrow.jl: the spec allows for "record batches", so it's natural to chunk up large tables into individual batches
* CSV.jl: now provides the `CSV.Chunks` iterator for chunking up really large csv files
* ODBC.jl: has a natural interface under the hood for iterating chunks of columns in a streaming-like way from the database

**Comment by EricForgy** [comment]
Cool 👍

I'd add XLSX.jl to your list. In financial services, a lot of data is still passed around via Excel and the data is often partitioned (if I understand what you mean).
