### ISSUE TITLE
Another weird constructor

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/Tables.jl#188]
```
julia> DataFrame([(rand(), rand()) for i in 1:10])
10×2 DataFrame
│ Row │ 1        │ 2        │
│     │ Float64  │ Float64  │
├─────┼──────────┼──────────┤
│ 1   │ 0.349645 │ 0.242401 │
│ 2   │ 0.561845 │ 0.478276 │
│ 3   │ 0.660003 │ 0.420934 │
│ 4   │ 0.766935 │ 0.650344 │
│ 5   │ 0.491957 │ 0.867926 │
│ 6   │ 0.137307 │ 0.267698 │
│ 7   │ 0.478357 │ 0.476889 │
│ 8   │ 0.72866  │ 0.871068 │
│ 9   │ 0.353402 │ 0.810791 │
│ 10  │ 0.078443 │ 0.686031 │

```

It's odd that the column names are `1`, `2`, instead of `x1`, `x2`. 

This stems from the fact that `Tables.columns` for a vector of tuples returns an object whose property names are `(Symbol("1"), Symbol("2"))`. 

Perhaps I am misunderstanding Tables.jl here. A vector of tuples isn't a table. Why does `Tables.columns` work, then?

**Comment by quinnj** [comment]
@bkamins is right; there are legitimate uses for treating tuples as rows, and as they have `propertynames` and `getproperty` defined w/ integers, that's how the column names play out (and this works at all). As noted, it's more useful for users to have control over column names, in which case they can wrap the tuples in Namedtuples.
