### ISSUE TITLE
Add trait for column scientific type

### ISSUE THREAD

**Issue by juliohm** [JuliaData/Tables.jl#190]
More and more often I am realizing that most algorithms actually need to be aware of the scientific type as opposed to the machine type. Could we have a trait like `Tables.columnscitype` besides the existing `Tables.columntype` that dispatches `ScientificTypes.scitype` on the column vector? It would return the type of the element of the vector as `Categorical`, `Continuous` or any scientific type.

**Comment by ablaom** [comment]
FYI: The ScientificTypes.jl is a super-lightweight package only providing the types and basic functionality. It does not implement a *convention* on how type should be converted. So:

```julia
using ScientificTypes
scitype(1.2)
julia> scitype(1.2)
┌ Warning: No convention specified. Did you forget to use the `set_convention` function?
└ @ ScientificTypes ~/.julia/packages/ScientificTypes/VHOpR/src/ScientificTypes.jl:75
Unknown
```

The only convention implemented is that in MLJScientificTypes.jl which, despite the prefix "MLJ" is intended for general use. So:

```julia
using MLJScientificTypes
julia> scitype(1.2)
Continuous
```

This package has these explicit dependencies: CategoricalArrays, ColorTypes, Dates, PrettyTables, ScientificTypes, 
Tables (!). 

Maybe there is an argument for a "mini-convention" which excludes ColorTypes and Tables?

**Comment by quinnj** [comment]
A couple of quick thoughts (without having researched ScientificTypes.jl at all):
* There actually is no `Tables.columntype` function
* This seems like the kind of thing that could just be its own API around the Tables.jl interface; i.e. you could have a ScientificTables.jl package that provided this `ScientificTables.scientifictype(tbl, i)` function that first called `Tables.getcolumn(tbl, i)` then `ScientificTypes.scitype(col)` on the returned column/vector.

While Julia doesn't have official or blessed ways to do interfaces/APIs, it _does_ provide remarkable ways of composing functionality _without_ needing to just add dependencies everywhere. This comment comes from a desire to avoid any new dependencies in Tables.jl, due to its proliferation in the package ecosystem and potential impact downstream.

**Comment by ablaom** [comment]
> This seems like the kind of thing that could just be its own API around the Tables.jl interface;

Yes, and this is essentially what we already do in MLJScientificTypes:

```julia
julia> X = (x=1:3, y=rand(3))
(x = 1:3, y = [0.43563412300680593, 0.5449494566834991, 0.8950265952201497])

julia> schema(X)
┌─────────┬─────────┬────────────┐
│ _.names │ _.types │ _.scitypes │
├─────────┼─────────┼────────────┤
│ x       │ Int64   │ Count      │
│ y       │ Float64 │ Continuous │
└─────────┴─────────┴────────────┘
_.nrows = 3


julia> ans.scitypes
(Count, Continuous)
```

**Comment by ablaom** [comment]
And `X` can be any Tables.jl table.

**Comment by ablaom** [comment]
But, as we also compute `rows`, this requires materialising the table in-memory, which Tables.schema does not.

**Comment by juliohm** [comment]
Thank you all for the comments.

@ablaom I have introduced my own scientific convention in GeoStatsBase.jl just because of the MLJ prefix in MLJScientificTypes.jl. It is pretty much the same convention copied/pasted. I wish the functionalities you mentioned above (which are quite useful in practice) were completely decoupled from any specific downstream project. I know that at the end the prefix MLJ doesn't make the implementation specific to the MLJ.jl project as you mentioned, but still, it signals developers that somehow this basic convention (which is quite standard and widely accepted in statistics) is part of MLJ.jl.

If you feel that a barebone version of the convention, including the `coerce` and `schema` functionality could be migrated to a `JuliaData/ScientificTables.jl` package as suggested by @quinnj , I'd be happy to join efforts.

**Comment by juliohm** [comment]
> While Julia doesn't have official or blessed ways to do interfaces/APIs, it _does_ provide remarkable ways of composing functionality _without_ needing to just add dependencies everywhere.

We've had a recent discussion on Zulip @quinnj about this lack of traits and interfaces. I don't think Julia currently provides the necessary mechanisms for more powerful collaborations across different ecosystems. Whenever we need to add a method to a function for objects satisfying a given trait, and this function does not belong to us, we are stuck or need a super convoluted approach with macros to implement the trait on the consumer side: https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/Extending.20a.20trait.20with.20another.20trait

**Comment by ablaom** [comment]
>  I wish the functionalities you mentioned above (which are quite useful in practice) were completely decoupled from any specific downstream project. 

They are. It's just the name. And the documentation explains all this in detail.

**Comment by ablaom** [comment]
> If you feel that a barebone version of the convention, including the coerce and schema functionality could be migrated to a JuliaData/ScientificTables.jl package as suggested by @quinnj , I'd be happy to join efforts.

This is only worthwhile if there are dependencies in MLJScientificTypes (eg, ColorTypes) that are burdensome. If so, I'm happy to support/guide but I don't have the resources to implement much.

> I have introduced my own scientific convention in GeoStatsBase.jl

Do you mean you build on the types in ScientificTypes or start from scratch?

**Comment by juliohm** [comment]
> Do you mean you build on the types in ScientificTypes or start from scratch?

I build on the types in ScientificTypes.jl, and just add the convention statements as suggested in the docs. My point is that the convention most people adopt, let's call it "canonical" convention where floats are continuous, integers are some sort of count, strings are text, etc has nothing do with a specific project. I still think that ScientificTypes.jl could provide this canonical convention to everyone as opposed to a separate MLJScientificTypes.jl package. The package dependencies there aren't really an issue in my opinion:

```julia
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
```

If someone is interested in ScientificTypes.jl to start with, it is reasonable to assume that they will be playing with these dependencies anyway or already have them installed in the project.

**Comment by ablaom** [comment]
So, in other words, `MLJScientificTypes` already provides a solution. You just don't like the name?

**Comment by juliohm** [comment]
I don't understand the rationale for the name :+1: and I don't understand why these efforts don't live in JuliaData or any other community-driven GitHub organization. These are the two main reasons I have to copy/paste my own convention currently.

**Comment by ablaom** [comment]
> I have to copy/paste my own convention currently.

So you copy and paste for a purely political reason, not because the functionality you require needs this?

**Comment by juliohm** [comment]
Yes, I am trying to avoid politics and any decision that requires input from specific institutions.

**Comment by quinnj** [comment]
I'd be happy to accept a ScientificTables.jl package or whatever in the JuliaData org if everyone things that would help in discoverability and having a more central place to manage things.

**Comment by juliohm** [comment]
That would certainly help with discoverability, maintenance and more people brainstorming these conventions.
