### ISSUE TITLE
adding Tables.table methods

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#199]
@quinnj would you be OK to allow `AbstracVector{Symbol}` and `AbstractVector{<:AbstractString}` as a `header` in `Tables.table`.

relevant for a decision in https://github.com/JuliaData/DataFrames.jl/issues/2433#issuecomment-695050438.

**Comment by quinnj** [comment]
Yes, that's fine by me; we can parameterize `MatrixTable` to accept any of these options, or just convert anything to `Vector{Symbol}`, I don't have a strong preference either way. If you want me to do it, just let me know, or feel free to do a PR.

**Comment by bkamins** [comment]
A proposal is in #200. Thank you! (@nalimilan - I am fully flexible there - more flexible than we are in DataFrames.jl but I think in Tables.jl which should be generic it should be OK; any opinion?)
