### ISSUE TITLE
What is a Table

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#208]
I am finishing https://github.com/JuliaData/DataFrames.jl/pull/2464. I do want to stick to what we agreed there, but because we are stricter in DataFrames.jl we start exposing things that I just think make no sense although they are valid (i.e. it is hard to imagine that someone would want such a behaviour). The example is:
```
julia> Tables.schema(Tables.columntable([categorical([1,2]), categorical([3,4])]))
Tables.Schema:
 :refs  Array{UInt32,1}
 :pool  CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}
```
Do we really have to be that flexible with what we accept as elements of a vector when we check if something is a table?

Maybe I am missing something here, but the current level of flexibility of Tables.jl seems to big for me.

CC @nalimilan, @quinnj, @pdeffebach, @oxinabox, @davidanthoff

**Comment by nalimilan** [comment]
Yes, it's quite weird to allow this kind of thing. However, I'm not sure how to avoid it as it's just a consequence of falling back to `propertynames` to get column names.

**Comment by bkamins** [comment]
> However, I'm not sure how to avoid it as it's just a consequence of falling back to `propertynames` to get column names.

I know, but still I really think it is problematic. Especially if these are properties of `AbstractVector` type as in this example (maybe we can do nothing about it, but the consequence is, at least in DataFrames.jl that people might silently get a completely different result in legacy codes).

As a partial solution maybe we should treat `AbstractVector` holding `AbstractVector`s as not-table (this is the most problematic case I think) unless some subtype of it explicitly opts-in to be `Tables.istable`?

**Comment by pdeffebach** [comment]
+1 to being restrictive. If someone wants to make a table out of a vector of custom structs they can use a `StructArray`. I like the `Tables.istable` check.

**Comment by nalimilan** [comment]
Maybe we could use `propertynames(x, false)`?

EDIT: though that doesn't make a difference for the OP example.

**Comment by quinnj** [comment]
I disagree; this is used all the time to treat normal iterators/vectors of custom structs (e.g. `Person` w/ `id`, `name`, etc. fields) and have them automatically treated as a table. It's come up much more often as a desired _feature_ than something unexpected w/ Tables.jl users.

I don't see anything wrong with catching this case specifically in DataFrames.jl to just throw an informative error and try to point the user to use the pairs/kwargs constructor or a NamedTuple of vectors.

**Comment by quinnj** [comment]
I'm not familiar with the private arg of `propertynames`; is that new? I'd be open to using non-private propertynames by default; that makes sense to me.

**Comment by pdeffebach** [comment]
Is there some lightweight `namedtuple` constructor we can use here to convert any struct to a namedtuple without copying? Then we could just tell people to use that.

**Comment by bkamins** [comment]
>  this is used all the time to treat normal iterators/vectors of custom structs (e.g. Person w/ id, name, etc. fields) and have them automatically treated as a table.

And I agree with this - in such case it makes a perfect sense.

The problem I have when you have an iterable (e.g. a vector) inside an iterator.

**Comment by nalimilan** [comment]
At least we could be stricter in DataFrames for some transition period to avoid confusion when removing old constructors.

> I'm not familiar with the private arg of `propertynames`; is that new? I'd be open to using non-private propertynames by default; that makes sense to me.

I'm not sure. I think it makes sense to use it, but in practice it is ignored by the generic fallback so it's probably not used that often. I think it's used by factorization objects to hide their internal fields.

**Comment by bkamins** [comment]
> At least we could be stricter in DataFrames for some transition period to avoid confusion when removing old constructors.

In my PR we are. It is now a deprecation warning only now.

@quinnj - if you feel it is undesired to change Tables.jl design here just close this issue please.

**Comment by rofinn** [comment]
Kinda sounds like a distinction between "private" vs "public" fields? Maybe we could just promote something like the `_<field>` approach from python?

**Comment by bkamins** [comment]
As a side note: it was in particular widely requested that vector of iterables in DataFrames.jl is expanded to multiple columns, so in 0.22 you will have the following:

```
select(DataFrame(col=["a b", "c d"]), :col => ByRow(split) => AsTable)
```
create two columns - one `["a", "c"]` and the second `["b", "d"]`.

I do not say that Tables.jl should follow this pattern (it probably should not) but I just wanted to note what pattern we will support in DataFrames.jl soon which is somewhat related.
