### ISSUE TITLE
`Tables.columntable(NamedTuple[])` errors

### ISSUE THREAD

**Issue by staticfloat** [JuliaData/Tables.jl#228]
It feels like `Tables.columntable()` should simply return `NamedTuple[]` if it is passed an empty collection.  As it stands, it currently errors:

```julia
julia> Tables.columntable(NamedTuple[])
ERROR: ArgumentError: type does not have a definite number of fields
Stacktrace:
 [1] fieldcount(::Any) at ./reflection.jl:725
 [2] buildcolumns at /home/sabae/.julia/packages/Tables/8Ud85/src/fallbacks.jl:206 [inlined]
 [3] columns at /home/sabae/.julia/packages/Tables/8Ud85/src/fallbacks.jl:253 [inlined]
 [4] columntable(::Array{NamedTuple,1}) at /home/sabae/.julia/packages/Tables/8Ud85/src/namedtuples.jl:158
 [5] top-level scope at REPL[2]:1
```

**Comment by bkamins** [comment]
`NamedTuple` is an abstract type and I think `Tables.columntable` should return something that has a well established schema (so that you can inspect it).

**Comment by quinnj** [comment]
Yes, so far we've been pretty conservative in only accepting `AbstractVector{<:NamedTuple}`. The alternative path is that we accept anything iterable that produces something property-accessible. So `NamedTuple[]` unfortunately doesn't fit in either of those paths. We did recently make a change to at least check if the empty iterator has a known `eltype` and if so, make an appropriate table based on that. We could consider further loosening what we work with here if we feel it makes sense.

It seems like we could return `NamedTuple{(), Tuple{}}[]`, which would at least be a concrete version of `NamedTuple[]`.

**Comment by staticfloat** [comment]
> Yes, so far we've been pretty conservative in only accepting `AbstractVector{<:NamedTuple}`.

I'm confused though:

```
julia> typeof(NamedTuple[]) <: AbstractVector{<:NamedTuple}
true
```

My typical workflow is to create a bunch of `NamedTuple`'s from my logfile parsing, then pass them through `columntable()` to get a nicely-compacted datastructure that I can then pass to/from `CSV`.

In the case that parsing completely fails and I have no parsed lines, I'd like to be able to emit an empty table (no rows or columns).  How do you suggest I do that?  Right now, I'm just manually returning `NamedTuple[]` in that case, as the isomorphism `columntable(X[]) == X[]` makes sense to me.

**Comment by bkamins** [comment]
Why do you need `NamedTuple` and not `NamedTuple{(), Tuple{}}`?

**Comment by staticfloat** [comment]
Oh, I don't!  Both are fine for me.  I just need an empty-like thing, and my attempt to create it failed with an error.

**Comment by bkamins** [comment]
```
julia> Tables.columntable(NamedTuple{(), Tuple{}}[])
NamedTuple()
```

**Comment by staticfloat** [comment]
Ah, I see what you mean.  My data analysis pipeline is quite simplistic:

```julia
parsed_lines = NamedTuple[]
while !eof(io)
    parsed = parse_log_line(readline(io), filename)
    if parsed !== nothing
        push!(parsed_lines, parsed)
    end
end
return Tables.columntable(parsed_lines)
```

How do you suggest I get a type signature like you have? I can't just directly use that type signature, I don't think, because I essentially want to allow the same codepath to work for both properly-parsed files (which I presume would have a very different type signature) and ones that don't parse properly at all (which would have the one that you just suggested).

**Comment by bkamins** [comment]
The simplest fix is:
```
return isempty(parsed_lines) ? (;) : Tables.columntable(parsed_lines)
```

**Comment by staticfloat** [comment]
Yep, that's pretty much what I'm doing right now.  My question though is why doesn't `columntable()` do that already?

**Comment by quinnj** [comment]
Because `columntable` takes any valid Tables.jl input and converts it to a NamedTuple of AbstractVectors. But an empty `NamedTupe[]` is not a valid table; if it was non-empty, that can be considered a row table. Let me look into the code a bit and see if we could assume empty is ok.

**Comment by quinnj** [comment]
Ok, digging into the code reveals this is actually a bug and technically a regression. Fix is up: https://github.com/JuliaData/Tables.jl/pull/229
