### ISSUE TITLE
How about an alias DictTable for Dict{Symbol,Vector{T}} where T

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#231]
We already have ColumnTable alias.

Our use case: wanting to give users option in an ML model to return either ColumnTable or DictTable; first is in the Tables.jl namespace but second is not.

Happy to make a PR.

@OkonSamuel

**Comment by quinnj** [comment]
We have `const DictColumns = AbstractDict{K, V} where {K <: Symbol, V <: AbstractVector}`; does that not work for your case?

**Comment by ablaom** [comment]
@quinnj Thanks!

@OkonSamuel What do you think?

**Comment by OkonSamuel** [comment]
perfect
