### ISSUE TITLE
Interface for `join` methods

### ISSUE THREAD

**Issue by iblislin** [JuliaData/Tables.jl#238]
Is it suitable for adding interface of inner/left/right/outer/semi/anti/cross-join methods here?
TimeSeries.jl also needs some of them for overloading and customizing for time axis.

**Comment by quinnj** [comment]
I think it would make more sense to define them in DataAPI.jl package; which exists specifically for sharing common (exported) methods from different packages.

**Comment by iblislin** [comment]
Ah, fine. I'm going to make a PR for them.

**Comment by bkamins** [comment]
Yes - it would be good to keep things consistent there. It should not lead to dispatch ambiguities fortunately.
