### ISSUE TITLE
coerce Tables.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaData/Tables.jl#240]
The functionality provided by `MLJ.coerce` now works with any Tables.jl table. It is extremely useful. Being able to take any table and reinterpret its columns with different scientific types from ScientificTypes.jl is an important building block in any data science project. @quinnj @bkamins @ablaom would it make sense to port this functionality over here for wider accessibility? Various projects that are not necessarily doing ML could benefit from this very nice work.

**Comment by bkamins** [comment]
We cannot use MLJ.jl defined types. What functionality exactly would you imagine to be added to Tables.jl?

**Comment by juliohm** [comment]
The proposal is about considering moving these types to ScientificTypes.jl if they are not there already and then moving the implementation of `coerce` to here. Makes sense? That would free everyone from loading the full ML stack just to coerce the columns of a table to the appropriate scientific type. I think that depends on @ablaom opinion.

It is really nice to just load a generic table and have a method to change a column to categorical type for example before plotting or doing some calculation. It is as simple as:

```julia
julia> using MLJ

julia> t = (a=[1,2,3], b=[4.0,5.0,6.0])
(a = [1, 2, 3],
 b = [4.0, 5.0, 6.0],)

julia> coerce(t, :a => Multiclass)
(a = CategoricalArrays.CategoricalValue{Int64, UInt32}[1, 2, 3],
 b = [4.0, 5.0, 6.0],)
```
So instead of importing MLJ.jl we would import Tables.jl

**Comment by bkamins** [comment]
I think it is too specific for Tables.jl. But what could possibly be done is a lightweight package in MLJ ecosystem that would do this and then you would load a single lightweight package.

**Comment by juliohm** [comment]
Can you explain why do you think it is too specific for Tables.jl?

**Comment by bkamins** [comment]
The objective of Tables.jl is to provide an interface functions not transformation functions.
There are other packages, like https://github.com/JuliaData/TableOperations.jl that are designed for operations on tables.

**Comment by juliohm** [comment]
I see. I think when I mention "Tables.jl" I have this broader Tables.jl ecosystem in mind that includes TableOperations.jl. If the `coerce` function could go in TableOperations.jl that would already be useful generalization.

**Comment by juliohm** [comment]
As a side comment, I think the entire ecosystem for data science would benefit from having scientific types treated more explicitly, starting with the change proposed here. Operating with machine types directly is rarely what we need.

**Comment by bkamins** [comment]
> I think the entire ecosystem for data science would benefit from having scientific types treated more explicitly

I agree

**Comment by quinnj** [comment]
The coerce method sounds like it could possibly live in DataApi.jl package

**Comment by ablaom** [comment]
> That would free everyone from loading the full ML stack just to coerce the columns of a table to the appropriate scientific type.

Happily, one does not need the full MLJ stack. One only requires MLJScientificTypes, whose only purpose is to implement a scitype *convention*, and add the associated `coerce`/`auto type` functionality. Despite the [regrettable name](https://github.com/alan-turing-institute/ScientificTypes.jl/issues/125) the only thing "MLJ" about the package is that it implements a convention that happens to be adopted in the MLJ eco-system.

The package ScientificTypes pretty much defines only the types; it does not implement a convention and is therefore able to have no dependencies.  

Apart from objections to the name, it seems to  me MLJScientificTypes already serves the poster's purposes, no?

**Comment by bkamins** [comment]
@ablaom - I have checked the package and it does exactly what I would assume it should do as commented above. Thank you for such a fine design.

**Comment by juliohm** [comment]
> Apart from objections to the name, it seems to me MLJScientificTypes already serves the poster's purposes, no?

Another question I have is if these efforts could be migrated to community-driven organizations. I am only asking this because as an ex-employer of IBM I don't have write access to repositories I used to work on that are hosted in the IBM GitHub organization. If you leave the Alan institute for some reason @ablaom , is there any chance that we will see ourselves in a similar situation? With community-driven organizations such as JuliaData we can join and leave institutions and still maintain software with the freedom we always had. Thanks for considering the changes and for this nice work on scientific types. It is super useful for teaching Julia to students who are familiar with statistics but not necessarily the low-level details of categorical types, etc.

**Comment by ablaom** [comment]
We are planning to move all the MLJ repos and cousins to a separate org, JuliaAI. That's not to say particular repositories, such as MLJScientificTypes (or renaming thereof) could not live somewhere else.

**Comment by juliohm** [comment]
That is amazing @ablaom , thank you for considering the proposal. Really awesome 👏🏽

**Comment by ablaom** [comment]
For the record, MLJScientificTypes has now been renamed ScientificTypes and ScientificTypes has been renamed ScientificTypesBase. Both repos now live at JuliaAI.

**Comment by juliohm** [comment]
Thank you @ablaom for the great work. Closing the issue.
