### ISSUE TITLE
support AbstractVecOrMat in matrix.jl

### ISSUE THREAD

**Issue by stevengj** [JuliaData/Tables.jl#243]
If you have an `AbstractVector`, it would be convenient to be able to treat it as a table with a single column via `table(x)`.   It seems like this could be implemented simply by replacing `AbstractMatrix` with `AbstractVecOrMat` in `src/matrix.jl`.

(Recall that Julia vectors can be indexed like a matrix, with two indices, as long as the second index is `1`, and that `size(x,2)` returns `1` when `x` is a vector.  This is precisely so that vectors can be treated as 1-column matrices.)

**Comment by bkamins** [comment]
Currently vectors are handled differently. Tables.jl checks the contents of the vector and deconstructs it if possible:
```
julia> Tables.columns([(a=1,b=2), (a=3,b=4)])
Tables.CopiedColumns{NamedTuple{(:a, :b), Tuple{Vector{Int64}, Vector{Int64}}}} with 2 rows, 2 columns, and schema:
 :a  Int64
 :b  Int64

julia> Tables.columns(["x"=>1, "y"=>2])
Tables.CopiedColumns{NamedTuple{(:first, :second), Tuple{Vector{String}, Vector{Int64}}}} with 2 rows, 2 columns, and schema:
 :first   String
 :second  Int64

julia> Tables.columns([(1, 2), (3, 4)])
Tables.CopiedColumns{NamedTuple{(Symbol("1"), Symbol("2")), Tuple{Vector{Int64}, Vector{Int64}}}} with 2 rows, 2 columns, and schema:
 Symbol("1")  Int64
 Symbol("2")  Int64
```

**Comment by stevengj** [comment]
@bkamins, I'm specifically talking about writing `table(x)` to construct a `MatrixTable` — this is currently only supported for `AbstractMatrix`, and throws a `MethodError` if `x` is a vector.

It seems consistent with typical Julia style to also accept a vector as a 1-column matrix in this context.

**Comment by bkamins** [comment]
Ah - I have missed this. Sorry for this.

So in this case I agree that `table(vector)` can be allowed. Thank you for clarifying.
