### ISSUE TITLE
are docs deploying correctly? latest tag is 1.5, latest docs is 1.2

### ISSUE THREAD

**Issue by anandijain** [JuliaData/Tables.jl#250]
https://tables.juliadata.org/stable/ latest is 1.2.1 and there is no dark mode. 

It looks like [CI](https://github.com/JuliaData/Tables.jl/runs/3316342403#step:4:17) is picking up an old version of Documenter.

mainly I just want dark mode 😆

**Comment by nalimilan** [comment]
Also needs https://github.com/JuliaData/Tables.jl/pull/252.
