### ISSUE TITLE
`Columns` is a lie

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/Tables.jl#254]
Calling `Columns` on a table does not always return something that `isa Columns`:

```julia
julia> using Tables

julia> rowdata = [(y=i, x=2i) for i in 1:10]
10-element Vector{NamedTuple{(:y, :x), Tuple{Int64, Int64}}}:
 (y = 1, x = 2)
 (y = 2, x = 4)
 (y = 3, x = 6)
 (y = 4, x = 8)
 (y = 5, x = 10)
 (y = 6, x = 12)
 (y = 7, x = 14)
 (y = 8, x = 16)
 (y = 9, x = 18)
 (y = 10, x = 20)

julia> coldata = Tables.Columns(Tables.columns(rowdata))
Tables.CopiedColumns{NamedTuple{(:y, :x), Tuple{Vector{Int64}, Vector{Int64}}}} with 10 rows, 2 columns, and schema:
 :y  Int64
 :x  Int64

julia> coldata isa Tables.Columns
false

julia> coldata isa Tables.CopiedColumns
true
```

For context, I'd hoped to replace `ColumnTable` with `Columns` in StatsModels, since `ColumnTable` packs a lot of extra information into the type parameters, being a named tuple.  But we currently use `NamedTuple` / `ColumnTable` as a dispatch target for methods of e.g. `modelcols`, and define a generic `modelcols(term, data) = modelcols(term, Tables.columntable(data))`.  I thought first that I could use `getcolumn` on any table, but that doesn't work with tables that where `columnaccess` is false.  The next thought was that I could replace `columntable` with `Columns(columns(data))` and `::ColumnTable` with `::Columns`, and that's what led me here...

**Comment by quinnj** [comment]
Thanks for the report; fix is up: https://github.com/JuliaData/Tables.jl/pull/255
