### ISSUE TITLE
columnaccess documentation clarification

### ISSUE THREAD

**Issue by tpgillam** [JuliaData/Tables.jl#257]
I was struggling a bit with implementing the interface for a column-table-like type, and eventually tracked it down to this part of the docs:

https://tables.juliadata.org/stable/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)

> Tables.columnaccess(table) |   | Declare that your table type defines a Tables.columns(table) method

I think one actually needs to define `Tables.columnaccess(::Type{MyTableType})`. The docstring of `columnaccess` doesn't mention this either from my reading. There is a default implementation `columnaccess(::T) where {T} = columnaccess(T)` [here](https://github.com/JuliaData/Tables.jl/blob/main/src/Tables.jl#L334-L335).

The method accepting the type is called in a number of places, for example [in rows()](https://github.com/JuliaData/Tables.jl/blob/main/src/fallbacks.jl#L87), so since I'd only defined `columnaccess(::MyTableType)`, `rows` didn't try to use the `RowIterator`.

Have I understood correctly? If so I'm happy to draft a PR to clarify the docs.

**Comment by tpgillam** [comment]
The same might apply to `istable`, `rowaccess` and `materializer` actually, from a very quick glance.

**Comment by quinnj** [comment]
Thanks for opening the issue! You correctly found that the use of `columnaccess` in the fallback `rows` definition incorrectly called `columnaccess` on the type and not the instance. _Uses_ of `columnaccess`/`istable`/etc should always be called on _instances_, whereas implementations should be defined on _types_ where possible. I've put up a fix in https://github.com/JuliaData/Tables.jl/pull/258.

I would appreciate a PR to help clarify any docs where this isn't clear.

**Comment by tpgillam** [comment]
That's great, thank you for the explanation! I'll draft something when I have a little time, hopefully in the next few days.
