### ISSUE TITLE
Creating DataFrame from Vector of NamedTuples with different names

### ISSUE THREAD

**Issue by rmsrosa** [JuliaData/Tables.jl#260]
This discussion arose in the Humans of Julia Discord server.

We thought it would be nice to be able to create a DataFrame directly from a Vector of NamedTuples even if the names are not all the same. For example, it works for `w` but not for `v` below:

```julia
julia> w = [(a = 1, b = 2), (a = 3, b = 4)]
2-element Vector{NamedTuple{(:a, :b), Tuple{Int64, Int64}}}:
 (a = 1, b = 2)
 (a = 3, b = 4)

julia> v = [(a = 1, b = 2), (a = 3, x = 4)]
2-element Vector{NamedTuple{names, Tuple{Int64, Int64}} where names}:
 (a = 1, b = 2)
 (a = 3, x = 4)

julia> DataFrame(w)
2×2 DataFrame
 Row │ a      b     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

julia> DataFrame(v)
ERROR: type NamedTuple has no field b
```

We can make it work with

```julia
julia> df = DataFrame()
0×0 DataFrame

julia> for a in v
           push!(df, pairs(a), cols = :union)
       end

julia> df
2×3 DataFrame
 Row │ a      b        x       
     │ Int64  Int64?   Int64?  
─────┼─────────────────────────
   1 │     1        2  missing 
   2 │     3  missing        4
```

It would be nice to have it work directly with `DataFrame(v)`, or even `DataFrame(v, cols = :union)`.

I attempted to think about a PR for that, but the implementation of `DataFrames(w)` was already too involved for me and I thought the loop above might not be the best solution.

I appreciate your comments/thoughts on this, and thank you for such a great package!

**Comment by bkamins** [comment]
I am transferring this issue to Tables.jl. The functionality you ask for is not a part of DataFrames.jl. `DataFrame` constructor delegates decision what is a table and how it should be handled to Tables.jl (there is no logic implemented for handling this case in DataFrames.jl).

@quinnj - what do you think about the proposal?

**Comment by rmsrosa** [comment]
Oh, I see. Ok, thanks!

**Comment by quinnj** [comment]
See the documentation for [`Tables.dictrowtable`](https://tables.juliadata.org/stable/#Tables.dictrowtable), which has this behavior; i.e. it will "union" the names/values from all rows for the final table output. So in your original example, you could do `df = DataFrame(Tables.dictrowtable(v))`. To make this work in the general case is prohibitive to performance; that is, to have the union behavior with a plain vector of namedtuples. The implementation just requires a lot more tracking/checking for the union behavior, so we ask users to opt-in explicitly by calling `Tables.dictrowtable`. We need to do some updates on the documentation so this is more clear.

**Comment by rmsrosa** [comment]
Thanks, @quinnj, for the comment. Indeed, `Tables.dictrowtable` makes things easier, albeit being four times slower than the push-loop above, at least in this case.

May I ask what is the "general case" you are referring to, other than the NamedTuples not having the same names?

**Comment by bkamins** [comment]
> "general case"

Table can be anything. It can e.g. be lazy with undefined number of rows.

> albeit being four times slower than the push-loop above, at least in this case.

I think @quinnj could consider adding a special method for `Tables.dictrowtable` for this specific input type?

**Comment by quinnj** [comment]
> albeit being four times slower than the push-loop above, at least in this case.

It's certainly not optimized for 2-row tables; I would suspect performance to be even or better on reasonably sized tables (1000s of rows). If that's not the case, then let's open an issue and I can try to take a look.
