### ISSUE TITLE
Why use NamedTuple data type?

### ISSUE THREAD

**Issue by HiramTheHero** [JuliaData/Tables.jl#267]
Hello All.

I hope you are well. This is a design question of Tables.jl. To my understanding, Tables.jl uses the NamedTuple data structure as its core type to work on. According to the help section on NamedTuples, it states "NamedTuples are immutable; neither the names nor the values can be modified in place after construction."

Because NamedTuple is immutable, I would think that this would cause some performance issues. (Such as, recreating a new NamedTuple anytime a change is performed.) What are the reasons why Tables.jl is built around NamedTuples instead of another, mutable, data structure?

I'm slowly gaining proficiency in Julia, so if my question is excessively naive, I apologize. Thank you for your time.

**Comment by bkamins** [comment]
`DataFrame` from DataFrames.jl is a mutable type you are asking for. The downside of being mutable is that the Julia compiler cannot easily optimize code using data stored in `DataFrame` (see https://docs.julialang.org/en/v1/manual/performance-tips/#Type-declarations for more explanations).
