### ISSUE TITLE
Make Tables.dictrowtable use OrderedDict

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#274]
It is debatable, but maybe it is better for `Tables.dictrowtable` to preserve the order of appearance of columns in the input by switching it to use `OrderedDict` internally?

**Comment by quinnj** [comment]
I agree this would be more consistent now that we use `OrderedDict` for `dictcolumntable`; perhaps we can request @mathieu17g to make a PR?

**Comment by bkamins** [comment]
Ah - indeed.

@mathieu17g - in #275 two things are missed:
* you updated `dictcolumntable` but also `dictrowtable` should be likewise updated
* the docstring of `dictcolumntable` should be fixed after your PR (as it mentions `Dict` incorrectly now)

would you be willing to make this PR?

**Comment by mathieu17g** [comment]
Yes I will look into it.
