### ISSUE TITLE
type of `NamedTuple`s returned from a row iterator w/ missing data

### ISSUE THREAD

**Issue by tpapp** [JuliaData/Tables.jl#28]
I am implementing Tables.jl row iterator interface for https://github.com/tpapp/StataDTAFiles.jl. I would like to keep it simple and have it return `NamedTuple`s, but I am unsure what's best in case the field types are not concrete. 

To make it concrete, suppose I have two columns `(:a, :b)` with element types `Tuple{Union{Missing,Int}, Union{Missing,Float64}}`. For rows `(a = missing, b = missing)` and `(a = 1, b = 1.0)`, should the iterator return
```julia
NamedTuple{(:a,:b),Tuple{Union{Missing,Int}, Union{Missing,Float64}}}((missing, missing))
NamedTuple{(:a,:b),Tuple{Union{Missing,Int}, Union{Missing,Float64}}}((1, 1.0))
```
or
```julia
NamedTuple{(:a,:b)}((missing, missing))
NamedTuple{(:a,:b)}((1, 1.0))
```
?

**Comment by nalimilan** [comment]
I think the former is better, since it ensures type stability, and it allows the consumer to allocate a column allowing for missing values in advance.

**Comment by nalimilan** [comment]
That said, I'm not sure named tuples can be efficient when there are many columns of varying types. What's your experience @quinnj?

**Comment by quinnj** [comment]
I agree the former is better. There's no efficiency concern for NamedTuples of non-concrete types. They're a tad more awkward when playing around at the REPL since the full types are printed (for concrete-typed NT, they're just printed liked you input them), but otherwise harmless. But in the case of Tables.jl, if the "schema" is always known for a given table at runtime, then all you really need to do is define `Tables.schema(t::MyTable) = Tables.Schema(names, types)`. Then it doesn't really matter what kind of NamedTuple you return, because "sinks" do pre-allocation based off the `Schema`.

**Comment by tpapp** [comment]
So just to clarify: having the second solution is not bad for the compiler either? Or at least not worse than the first one? Does either benefit from the "small unions" feature?

**Comment by nalimilan** [comment]
AFAIK the second solution is very bad for the compiler, as the return type isn't inferred to a small `Union` for each field, but at the tuple level, which gives 2^N different tuple types if each field contains some missing values. So currently this is just inferred as `NamedTuple`:
```julia
julia> f() = rand() > .5 ? (a=1, b=2, c=3) : rand() > .5 ? (a=1, b=missing, c=3) : (a=missing, b=missing, c=missing)
f (generic function with 1 method)

julia> @code_warntype f()
Body::NamedTuple
...
```

@quinnj When I said performance of `NamedTuple` could be bad, I was thinking about the problems with the compiler not being able to infer the types when there are lots of columns with different types. Isn't that a problem in practice?

**Comment by quinnj** [comment]
@nalimilan, no I haven't seen many issues w/ large NamedTuples. Now, I say that having worked w/ datasets w/ columns into the hundreds, but I imagine there are limits if you start talking datasets w/ columns in the thousands.
