### ISSUE TITLE
`Tables.Columns` accepts table sources as input rather than `AbstractColumns` as stated in its docstring

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaData/Tables.jl#283]
Looking at the lines of code [here](https://github.com/JuliaData/Tables.jl/blob/main/src/Tables.jl#L250-L266), I noticed that `Tables.Columns` accepts any table source as input instead of  `AbstractColumns` interface object as reported in its docstring. I think this would pose issue for input sources that don't have the property `Tables.columns(Tables.columns(x)) == Tables.columns(x)`, since the `Tables.Columns` constructor calls `Tables.columns`.
Or am I missing something? Was there a particular reason for this?
cc. @nalimilan , cc. @bkamins

**Comment by nalimilan** [comment]
I think the key word in the docstring is "interface":
>  wrap any `AbstractColumns` interface object

The input is required to satisfy the interface, but not necessarily the type. This could be made a bit more explicit.

Why do you think `Tables.columns(Tables.columns(x)) == Tables.columns(x)` is a required property?

**Comment by OkonSamuel** [comment]
Let say I have a particular table source say `x::MyTable`, Then I locally call `Tables.columns` on `x` to give an object `y::MyColumns`. If I then try to call `Tables.Columns` on `y` I should get an error since I haven't defined `y::MyColumns` as a `Table` or defined `Tables.columns(y::MyColumns) = y`.  It would fail because of [this](https://github.com/JuliaData/Tables.jl/blob/main/src/Tables.jl#L263) line.

**Comment by OkonSamuel** [comment]
So my point is that in General calling `Tables.Columns` on an  object resulting from a call to `Tables.columns` would throw an error.
For the case of `DataFrameColumns` object this just works because of [this](https://github.com/JuliaData/DataFrames.jl/blob/main/src/other/tables.jl#L88) line. Hence `DataFrame` source satisfies the property `Tables.columns(Tables.columns(x)) == Tables.columns(x)`

**Comment by bkamins** [comment]
> For the case of `DataFrameColumns` object this just works

I would say this is a whole point of the "interface" issue. It is responsibility of the provider of a type supporting Tables.jl table interface to implement all required methods.

However, I agree that it might not be always obvious how to do it.

@quinnj - maybe we could improve [this part](https://tables.juliadata.org/stable/#Implementing-the-Interface-(i.e.-becoming-a-Tables.jl-source)) of the documentation to make it clearer how things should be implemented.

In DataFrames.jl we have a recent related discussion in https://github.com/JuliaData/DataFrames.jl/issues/3054. I was not sure if we should treat `DataFrameRows` and `DataFrameColumns` as Tables.jl tables, or just as as objects returned by `Tables.rows` and `Tables.columns` that do not have to provide Tables.jl tables interface support. This is exactly related to your question. Let us see what @quinnj says (or maybe @nalimilan has some clear opinion here 😄).

**Comment by nalimilan** [comment]
It's true that the docstring for `AbstractColumns` doesn't say anywhere that `Tables.columns` should be implemented. And the docstring for `Tables.Columns` says that the passed argument must be `AbstractColumns`-like, but actually any Tables.jl table will work since `Tables.columns` is called on it. Maybe the docs just need being adapted.

**Comment by quinnj** [comment]
Yeah, I think this is just an outdated docs problem. Originally, we said that `Tables.Columns` usage was going to require `Tables.Columns(Tables.columns(x))`, i.e. as the docs state, you need to pass the result of `Tables.columns` to it. But in reality, that's pretty tedious and we decided for convenience that you should just be able to call `Tables.Columns(x)` and it would call `Tables.columns` for you. I can update the docs to something like: `Tables.Columns(x)` can be called on any `x` object that implements the Tables.jl interface for `Tables.columns` or `Tables.rows`.
