### ISSUE TITLE
`Tables.dictcolumntable` results in `#undef` values

### ISSUE THREAD

**Issue by ericphanson** [JuliaData/Tables.jl#289]
```julia
table = [(; c=""), NamedTuple()]
```
results in 
```julia
julia> Tables.dictcolumntable(table).c
2-element Vector{Union{Missing, String}}:
    ""
 #undef
```
on Tables v1.7.0.

I believe it should be `missing` instead. `Tables.dictrowtable` does `missing` for this example.

**Comment by bkamins** [comment]
Have you checked `main` branch? Maybe it is fixed already with https://github.com/JuliaData/Tables.jl/commit/d741e34cffb27afc214777b8ab5c87a31ad10486

**Comment by ericphanson** [comment]
Yes, it seems to be, good point. I would appreciate a release!

**Comment by bkamins** [comment]
CC @quinnj
