### ISSUE TITLE
Support 'tables' based on parameterized queries

### ISSUE THREAD

**Issue by timotaularson** [JuliaData/Tables.jl#29]

**Comment by nalimilan** [comment]
Please be more specific.

**Comment by quinnj** [comment]
Closing in favor of https://github.com/JuliaDatabases/ODBC.jl/issues/210, since I think that's the real request.

**Comment by timotaularson** [comment]
While that was the motivating request, I opened this issue because I thought it would be generally useful for a 'table' source to be able to support parameters. I will be more specific as you requested.

The schema currently provides names and types, which are both column-level details.
There should also be a way to express table-level details.

Some examples include specifying the presence of or need for multi-column indexes, whether the table is persisted or ephemeral, most efficient access patterns (e.g. by row or by column, sequential or random), and my original use case of parameters in case the 'table' is not a direct representation of data but a view/query against a larger data source.

In each of these examples something of specific concern to a table interface is being expressed about the data which is stored in or accessed via the rows and columns, but the information is table-level and cannot be expressed well just at the column (name, type) level.
