### ISSUE TITLE
`OrderedDict` deprecation in `DictColumnTable`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Tables.jl#294]
I'm getting the following deprecation warning from `OrderedCollections`, apparently due to `DictColumnTable` trying to make a deprecated conversion
```
┌ Warning: Conversion to OrderedDict is deprecated for unordered associative containers (in this case, Dict{Symbol, PyArray{T, 1, true, true, PythonCall.UnsafePyObject} where T}). Use an ordered or sorted associative type, such as SortedDict and OrderedDict.
```

**Comment by bkamins** [comment]
This is a quite bad deprecation. What is then a recommended way to convert a `Dict` to `OrderedDict`?

**Comment by ExpandingMan** [comment]
Hm, maybe I was running this on an older version of `OrderedCollections` because I'm doing `OrderedDict(::Dict)` and I'm not getting the warning... I'm confused.

**Comment by ExpandingMan** [comment]
Yeah, I'm really confused, I only seem to be getting this when using `PythonCall` for some table conversions from Python.  I don't understand how that package causes this warning but just converting directly doesnt...

**Comment by bkamins** [comment]
Maybe open an issue in DataStructures.jl and someone will know?

**Comment by ExpandingMan** [comment]
Oh wait, I found it... you are just not supposed to call `convert`, using the constructor is fine... so, for example:
```julia
◖◗ convert(OrderedDict{Int,Int}, Dict(1=>2))
┌ Warning: Conversion to OrderedDict is deprecated for unordered associative containers (in this case, Dict{Int64, Int64}). Use an ordered or sorted associative type, such as SortedDict and OrderedDict.
│   caller = top-level scope at REPL[2]:1
└ @ Core REPL[2]:1
OrderedDict{Int64, Int64} with 1 entry:
  1 => 2

◖◗ OrderedDict(Dict(1=>2))
OrderedDict{Int64, Int64} with 1 entry:
  1 => 2
```

I don't see `convert` in `dictcolumntable` so it must be an implicit conversion in an assignment but I'm not sure where.

**Comment by ExpandingMan** [comment]
While arguably `Tables.jl` should provide more constructors for `DictColumnTable`, it turns out the above was not really a Tables.jl issue because the package that was calling the warning was calling `DictColumnTable` directly and that package was what was improperly converting a `Dict`, see [this PR](https://github.com/cjdoris/PythonCall.jl/pull/221).  I suppose this is a bit of a "Julia has no private constructors" issue.

Anyway, nothing to be done here, so closing.
