### ISSUE TITLE
Allow table type to specify constructor as part of the interface

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#32]
I think this is not part of the interface as of now, but it'd be nice to have a way to know, for a given type that respects the table interface, how to build a table of that type.

The use case is that we may have some table operation that we want to work on any table, like

```julia
function mygroupby(s::T, args...) where {T}
  ....
  return t
end
```

If `t` is table-like, one may want to recreate a table of type `T` from `t` (for example, build back a `DataFrame`).

**Comment by quinnj** [comment]
What should we call this? A few ideas that come to mind:
* `Tables.sinkfunction`
* `Tables.sink`
* `Tables.constructor`

**Comment by quinnj** [comment]
This also gets a little murky when considering, for example, CSV.jl. The `CSV.File` type implements the Tables.jl source interface, but `CSV.write` takes any Tables.jl source and writes out a csv file. I guess we need to clarify what exactly we're after here and the expected use-cases: taking Tables.jl sources and returning some kind of in-memory structure? Just getting the sink function to a corresponding source type?

**Comment by piever** [comment]
I initially thought as `Tables.constructor` as a name, so if that also came to your mind independently I guess it's a good solution.

The purpose is to be able design "table-implementation independent" packages that also return tables. For example, I'm creating a set of widgets to do manipulations on tabular structures from a GUI. I'd like to support anything that implements the `Tables` interface. I assume that if the user run some operations from the GUI on a `DataFrame`, even though under the hood I'm not using anything from DataFrames but just the `Tables` machinery, I expect they'd like my GUI to give them back a `DataFrame`. Similarly for `IndexedTable`.

I would define both a trait `Tables.hasconstructor` to specify whether there is a constructor that makes sense (which in the case of `CSV.File` I guess there isn't) and a `Tables.constructor` function that returns the specific constructor. In this way for example in the case of the GUI, if one gets as input a `DataFrame`, or `IndexedTable` or `TypedTable` or `Array{NamedTuple}` or what not the GUI would return the corresponding structure. If one instead starts with some structure for which this is impossible or ill-defined (like a csv file for example), I think it makes sense to default to return a lazy table.

**Comment by piever** [comment]
> Just getting the sink function to a corresponding source type?

This would be enough: return a function that can ingest any table and return something of the source type (as mentioned above, I believe that for user unaware of Tables it can be a usability improvement in many cases to get something of the type they're familiar with - e.g. `DataFrames` - rather than some abstract table object).

**Comment by quinnj** [comment]
Couple of thoughts:
* We could maybe make `Tables.constructor` be "here's the preferred in-memory structure for this table"; that would allow, e.g. `CSV.File` to define `Tables.constructor(::Type{<:CSV.File}) = DataFrame`
* We could make a fallback be `Tables.constructor(T) = columntable`

**Comment by piever** [comment]
I completely agree on both points!

**Comment by nalimilan** [comment]
If it's allowed to build an object of a different type, I'd rather not call it `constructor`...

**Comment by joshday** [comment]
Just catching up with this issue!  I've wanted the same feature and haven't gotten around to putting work into it.

> here's \<the constructor for> the preferred in-memory structure for this table

`Tables.materializer`?

**Comment by nalimilan** [comment]
Why not. Or maybe we could use `similar` for this?

**Comment by quinnj** [comment]
I like `Tables.materializer` probably the best; I feel like `similar` has the same problem as `constructor`: I'd kind of expect to get the same kind of thing out. Does anyone feel like taking a crack as this? I won't have a chance to get to it for a couple days, so if anyone wants to contribute in the mean time, feel free. Otherwise, I'll have a go next week sometime.

**Comment by nalimilan** [comment]
> I feel like `similar` has the same problem as `constructor`: I'd kind of expect to get the same kind of thing out.

`similar` is documented to "Create an uninitialized mutable array with the given element type and size,   based upon the given source array." There is no guaranty that the result has the same type, which isn't possible for immutable arrays (notably ranges).
