### ISSUE TITLE
Tables.columntable contract

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#324]
The current contract of `Tables.columntable` is:

> Takes any input table source x and returns a `NamedTuple` of `Vector`s

However, this contract is not enforced, as `AbstractVector` other than `Vector` can be returned.

@quinnj - what is intended (should docstring be fixed or implementation?).

**Comment by quinnj** [comment]
I think the docstring should be updated. I think it makes sense to just have `AbstractVector` as the constraint on return type.

**Comment by bkamins** [comment]
OK - I have opened #325 to discuss this.
