### ISSUE TITLE
Interface on extracting row index

### ISSUE THREAD

**Issue by iblislin** [JuliaData/Tables.jl#40]
Hi, I'm working on a PR about the Tabls.jl integration for TimeSeries.jl.
https://github.com/JuliaStats/TimeSeries.jl/pull/382/files#diff-17226d5590764ff7e308bfa5045dacfaR3

Here is the initial try:
```julia
julia> using MarketData, DataFrames

julia> DataFrame(ohlc)                                                                                                
500×4 DataFrame
│ Row │ Open    │ High    │ Low     │ Close   │
│     │ Float64 │ Float64 │ Float64 │ Float64 │                                                                       
├─────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ 104.88  │ 112.5   │ 101.69  │ 111.94  │
│ 2   │ 108.25  │ 110.62  │ 101.19  │ 102.5   │
│ 3   │ 103.75  │ 110.56  │ 103.0   │ 104.0   │
│ 4   │ 106.12  │ 107.0   │ 95.0    │ 95.0    │
│ 5   │ 96.5    │ 101.0   │ 95.5    │ 99.5    │ 
│ 6   │ 102.0   │ 102.25  │ 94.75   │ 97.75   │
│ 7   │ 95.94   │ 99.38   │ 90.5    │ 92.75   │
...
```
but now I'm facing a problem: There is a time index in the design of `TimeSeries.TimeArray`.
The time index is used as the row indexing.
e.g.
```julia
julia> ohlc
500×4 TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2001-12-31
│            │ Open   │ High   │ Low    │ Close  │
├────────────┼────────┼────────┼────────┼────────┤
│ 2000-01-03 │ 104.88 │ 112.5  │ 101.69 │ 111.94 │
│ 2000-01-04 │ 108.25 │ 110.62 │ 101.19 │ 102.5  │
│ 2000-01-05 │ 103.75 │ 110.56 │ 103.0  │ 104.0  │
│ 2000-01-06 │ 106.12 │ 107.0  │ 95.0   │ 95.0   │
│ 2000-01-07 │ 96.5   │ 101.0  │ 95.5   │ 99.5   │
│ 2000-01-10 │ 102.0  │ 102.25 │ 94.75  │ 97.75  │
│ 2000-01-11 │ 95.94  │ 99.38  │ 90.5   │ 92.75  │
...
```

I think for a table-like data structure, there are two kind of indexing -- row and column.
Talbles.jl already provides the column index information via `Tables.Schema`, but not for row index.
In that WIP PR in TimeSeries.jl, if user create a `DataFrame` from `TimeArray`, the information about time index is missed. I think Tables.jl needs to take care about the row index as well. E.g. perhaps `DataFrame` will be able to set up an extra column for the data structure that contains non-traditional row index.

**Comment by quinnj** [comment]
Hmmmm, I'm not sure I quite understand, but here are some thoughts: 
* DataFrames doesn't really have a concept of "special" columns like a row index or anything, so I don't think there's really much a DataFrame could do special here for TimeSeries. Intuitively, I would just expect the time series index to become the first column in the DataFrame. cc: @nalimilan @bkamins 
* Going the other way around, i.e. converting a DataFrame => TimeArray, I would expect that the "Tables.jl" constructor would have a keyword argument where I could pass an integer or symbol corresponding to the DataFrame Date/DateTime column that should be used as the row index. Something like: `TimeArray(df; index=:columnA)`.

Does that make sense? I'm not sure what else the Tables.jl interface itself would need to change or support to help here. At least in this case, the "row index" seems specific to TimeArray, so it doesn't seem like Tables.jl would really do anything further to help. For example, a database has a slightly different notion of a "row index" that is usually a dedicated B-Tree datastructure to facilitate searching, but I'm not sure there's an apples-to-apples way to have different table format "row index"-like things talk to each other. I think there's a lot of flexibility in the individual sinks to add additional support for things like this.

**Comment by iblislin** [comment]
> Intuitively, I would just expect the time series index to become the first column in the DataFrame. 

To setting up an extra column on conversion from `TimeArray` to `DataFrame`,
there are some ways to implement it:
Adding the constructor like `DataFrame(::TimeArray)` to the `DataFrame.jl` or `TimeSeries.jl`, 
but this introduces (unwanted) dependency.
So, I want some interface on Tables.jl to deliver some information of row index.

The same story will happen on the other package, like `CSV.jl`. If user want to write TimeArray into a csv file via `CSV.jl`, there aren't an easy way to include the time index directly.

**Comment by iblislin** [comment]
> For example, a database has a slightly different notion of a "row index" that is usually a dedicated B-Tree datastructure to facilitate searching, but I'm not sure there's an apples-to-apples way to have different table format "row index"-like things talk to each other.

I don't expect there's an apples-to-apples way in all cases. but I want some interfaces to reveal "hey, there is non-traditional row index available in this data structure. When you consume columns, you might want to checkout the row index as well. It's optional."
Then, I can send some PRs to those pkg applies Tables.jl without adding `TimeSeries.jl` as their dependency.

So... in case of database, I won't want to release the info about row index;
In case of `TimeArray`, I will want to deliver the row index (time index).

This is my imagination (well, although this naming is quite bad):
```julia
Talbes.row_index_access(x::TimeArray) = true
...
```

**Comment by iblislin** [comment]
> Going the other way around, i.e. converting a DataFrame => TimeArray, I would expect that the "Tables.jl" constructor would have a keyword argument where I could pass an integer or symbol corresponding to the DataFrame Date/DateTime column that should be used as the row index. Something like: TimeArray(df; index=:columnA).

yeah, in my PR, I'm implementing stuff in that way via `Tables.Schema`.
https://github.com/JuliaStats/TimeSeries.jl/pull/382/files#diff-17226d5590764ff7e308bfa5045dacfaR24

Other data types to `TimeSeries.jl` are fine. We can carefully craft our constructor.

**Comment by nalimilan** [comment]
Maybe TimeSeries sources should just add the time index as the first column of the schema, so that sinks automatically preserve that information? AFAICT you always want it unless the sink is aware of TimeSeries and wants to do something special with the time information.

I agree it could make sense to be able to indicate that a column is a key or an index, though. That could be useful to preserve keys from databases, or to transform row indexes into array names (with NamedArrays or AxisArrays). But I think these are two quite different kinds of special columns which cannot be conflated.

**Comment by davidanthoff** [comment]
Maybe just go with the same design that I'm using for [IterableTables.jl](https://github.com/queryverse/IterableTables.jl) for this integration? See http://www.queryverse.org/IterableTables.jl/stable/userguide.html#TimeSeries-1 and https://github.com/queryverse/IterableTables.jl/blob/master/src/integrations/timeseries.jl.

**Comment by iblislin** [comment]
@nalimilan 
> Maybe TimeSeries sources should just add the time index as the first column of the schema, so that sinks automatically preserve that information? AFAICT you always want it unless the sink is aware of TimeSeries and wants to do something special with the time information.

I have tried to add something in to the schema.
but the `propertynames(x)` in the following code breaks the assumption.
https://github.com/JuliaData/DataFrames.jl/blob/0aeb2834d9c94cc3f82472cb261d98e1b5aa6a9f/src/other/tables.jl#L13

e.g. says `ohlc` is a `TimeArray`.
```julia
julia> propertynames(ohlc)
4-element Array{Symbol,1}:
 :Open 
 :High 
 :Low  
 :Close
```
So, If I tried to mock up the `Table.Schema` with an extra column, the construction in `DataFrame` 
will popup error:
  - `Index(collect(Symbol, propertynames(x))` got 4 symbols.
  - `Any[getvector(c) for c in Tables.eachcolumn(x)` got 5 columns.

So I'm talking about there are no way to notify the consumer "We (TimeArray) have extra stuffs" in [previous comment](https://github.com/JuliaData/Tables.jl/issues/40#issuecomment-433633026).

---
@davidanthoff I read the docs, but don't figure out the way for consuming a `TimeArray` to create a `DataFrame`. 
Only found the the way `DataFrame` -> `TimeArray`, but it is not an issue. 
I implemented it in my PR already. (https://github.com/JuliaData/Tables.jl/issues/40#issuecomment-433633613)
The issue is that `TimeArray` -> `DataFrame` or `TimeArray` -> `CSV` will lose the information of time index.

**Comment by davidanthoff** [comment]
It just adds a column called ``timestamp`` for that index, see [here](https://github.com/queryverse/IterableTables.jl/blob/d535652d2c23eb0c7080ff5abf50dd72c3e05b38/src/integrations/timeseries.jl#L16).

**Comment by iblislin** [comment]
> I agree it could make sense to be able to indicate that a column is a key or an index, though. That could be useful to preserve keys from databases, or to transform row indexes into array names (with NamedArrays or AxisArrays). But I think these are two quite different kinds of special columns which cannot be conflated.

@nalimilan 
hmm, I think I cannot understand this paragraph clearly, could you tell more?

**Comment by iblislin** [comment]
@davidanthoff ah, I see.
you also added an additional constructor `DataFrame`, right? so, the conversion works together.

**Comment by davidanthoff** [comment]
No, all I did there is return an iterable table that has a column called ``timestep``, plus all the columns from the ``TimeArray`` type. IterableTables.jl used to add a constructor to DataFrames.jl, but all of that functionality now lives in the DataFrames.jl package and that should really be enough to get this working.

**Comment by iblislin** [comment]
Does this work now? https://github.com/queryverse/IterableTables.jl/blob/d535652d2c23eb0c7080ff5abf50dd72c3e05b38/src/integrations/dataframes.jl#L21-L22
I think this is an additional constructor.

**Comment by iblislin** [comment]
ohhh, following the idea of extra column, I made this patch, works fine for DataFrame:
https://github.com/JuliaStats/TimeSeries.jl/pull/382/commits/8f9bfa9857e88569c6c7ad24c98b68370944fa57

I think the key is to pet the `Table.eachcolumn`:

```julia
Tables.columns(ta::TimeArray) = ta
```
to
```julia
Tables.columns(ta::TimeArray) = Tables.eachcolumn(ta)
Tables.eachcolumn(i::TableColumnIter) = i
```

**Comment by iblislin** [comment]
I think absorbing the time index into columns is the easiest way for TimeSeries.
Thanks @quinnj, @nalimilan and @davidagold for this discussion.

**Comment by davidanthoff** [comment]
> I think this is an additional constructor.

That code is only loaded if you are on an old version of DataFrames.jl that doesn't have the Tables.jl/TableTraits.jl integration in the DataFrames.jl package itself.

**Comment by iblislin** [comment]
@davidanthoff ah... what is the relationship between Tables.jl and TableTraits.jl?
If I finish the Tables.jl integration, do we still need the code about TimeSeries in IterableTable?

**Comment by davidanthoff** [comment]
I think the way to handle this right now is to add both the Tables.jl and the TableTraits.jl integration directly to TimeSeries.jl and not have anything in IterableTables.jl. If you just add Tables.jl integration in TimeSeries.jl, it will almost certainly conflict with the existing integration with TableTraits.jl in IterableTables.jl (because they probably both add a constructor that tries to catch everything).

You might be able to use some of the functionality in Tables.jl to help you implement the TableTraits.jl integration, but I'm not entirely sure, given that the storage format in TimeSeries.jl is actually not a vector of vectors. So it might also just be easier to copy the code from IterableTables.jl over and just run with that (at least we know it works).

There is a general discussion about the relationship between Tables.jl and TableTraits.jl [here](https://discourse.julialang.org/t/tables-jl-vs-tabletraits-jl-was-textparse-jl-is-fast-again/16982/20)
