### ISSUE TITLE
propertynames doesn't constant infer

### ISSUE THREAD

**Issue by bramtayl** [JuliaData/Tables.jl#47]
I think for an interface for this to really be useful, Base should work a bit harder to get propertynames to constant infer. Otherwise, most common row-wise operations won't be type stable (see examples here https://github.com/bramtayl/LightQuery.jl/blob/49706713e6e5035c3bee5e85bb4acfea189037f3/src/LightQuery.jl#L110)

**Comment by piever** [comment]
A similar problem came up for `fieldnames` in StructArrays, maybe https://github.com/JuliaLang/julia/issues/29100 is a relevant issue.

**Comment by bramtayl** [comment]
Yeah same root cause
