### ISSUE TITLE
0.13.0 Release Broken

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/Tables.jl#53]
The REQUIRE file is missing dependencies in the Project.toml. This makes it that Tables.jl fail to precompile. The patch should fix it.

**Comment by Nosferican** [comment]
With #54 merged, the patch release should be merged ASAP (maybe a manual trigger to propagate to General?, won't have any changes to METADATA). The 0.13.0 should probably be yanked (@StefanKarpinski could you confirm we should yank that release version since it just fails to precompile). Once these steps are done, this issue should be closed.

**Comment by quinnj** [comment]
The new tag v0.1.14 has been merged in METADATA.

**Comment by Nosferican** [comment]
I think we can close this issue now. To be super save we could ask to yank the 0.1.13 release on General, but since it was less than a day as the latest release it should hopefully be fine regardless.
