### ISSUE TITLE
is a Matrix a table?

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaData/Tables.jl#56]
Tables considers a `Matrix{Any}` to be a table but gives non-sensical output for `columns`, `rows`, etc.:

```julia
julia> d = Matrix{Any}(hcat(1:10, rand(10)))
10×2 Array{Any,2}:
  1.0  0.36329 
  2.0  0.742311
  3.0  0.250377
  4.0  0.738728
  5.0  0.949255
  6.0  0.703505
  7.0  0.269327
  8.0  0.826039
  9.0  0.564706
 10.0  0.401836

julia> Tables.istable(d)
true

julia> Tables.columns(d)
NamedTuple()

julia> Tables.rows(d)
Tables.DataValueUnwrapper{Array{Any,2}}(Any[1.0 0.36329; 2.0 0.742311; … ; 9.0 0.564706; 10.0 0.401836])

julia> Tables.rows(d) |> first
Tables.DataValueUnwrapRow{Float64}(1.0)
```

**Comment by quinnj** [comment]
Yeah, this is a good question. I'm working now on cleaning up the logic in Tables.jl. We could add support for Matrix as a table, but what should it look like? Generate column names?

**Comment by kleinschmidt** [comment]
I think it should _not_ be a table actually, and as far as I could tell it's just `Matrix{Any}`, and not e.g. `Matrix{FLoat64}` that is considered a table.

**Comment by nalimilan** [comment]
`DataFrame(::Matrix)` is supported and generates column names `x1`, `x2`, etc. I'm not super convinced either way, but why not allow matrices to be used as tables?

**Comment by tpapp** [comment]
I would be conservative and only support types which are really meant to be something that maps to a `DataFrame`, in the sense that if I convert to `T` and then back to `DataFrame`, I get more or less the same thing back, of course with possibly different (narrower) column types etc.

**Comment by kleinschmidt** [comment]
@nalimilan because they're not "property-addressable collections of iterables"...it just feels too punny

**Comment by quinnj** [comment]
Yeah, I think having `DataFrame(x::Matrix)` makes this a lot easier to not support in Tables.jl. I've actually been doing some refinements on the Tables interface yesterday/this morning, so hopefully I'll get a PR up tonight that should clean things up, including this case.

**Comment by JeffBezanson** [comment]
I agree with *not* making matrices tables for now. The example that comes to mind is sparse matrices. Sparse and dense matrices are just different representations of exactly the same thing. But it is natural to think of sparse matrix operations as relational operations on a table with I, J, V columns. The same interpretation would have to apply to dense matrices, but that's probably not what people want. So you should have to be quite explicit.

**Comment by quinnj** [comment]
We now have two "integration" functions for allowing easy use of matrices in the table world; while `AbstractMatrix` are not treated automatically as tables, a user can easily do `Tables.table(matrix)` to get a Tables.jl-interface compatible object; as well as `Tables.matrix(table)` to turn any Tables.jl-interface compatible object into a matrix.

**Comment by nalimilan** [comment]
See also the question of whether a `NamedMatrix` is a table: https://github.com/davidavdav/NamedArrays.jl/issues/76.
