### ISSUE TITLE
Usage: What's the proper way to select rows of a table with source type = sink type?

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#57]
I want to write a function that takes any object implementing the Tables.jl interface (as source and sink) and returns an object of identical type,  but restricted to some rows (or columns). That is, how to I get `materialize` to output a table of the same type as was input?

**Comment by joshday** [comment]
Not sure I understand the question.  Are you looking for `Tables.materializer` (bottom of README)?

**Comment by tpapp** [comment]
I don't understand the question either, an MWE would help.

**Comment by ablaom** [comment]
With `materializer` it seems I have no choice about the sink - this is predetermined by the implementer. 

Suppose I have a `DataFrame` and I want a new `DataFrame` with just rows 5:8. Or I have a `TypedTables.Table` and I want a new `TypedTables.Tabel` with just rows 5:8. I want a generic function to do this, i.e. one that works on any type implementing the `Tables` API. The caller of this function has no idea about the type but wants the *same* type as output.

**Comment by joshday** [comment]
That's exactly the use case `materializer` is for.  It should return the default sink function for a table.  We say "default sink function" instead of "sink function that creates the same type" because some tables like `CSV.File` are lazy and don't "exist", so its materializer can't be the same type.

Currently it appears DataFrames is missing a `materializer` method and uses the fallback definition of `columntable`.

**Comment by ablaom** [comment]
Thanks for the clarification. 

Is there a way of querying whether a given type can act as sink and, if so, insisting that it be used as the sink type to be materialised, even if the provider of that type has not overloaded `materialiser` for his type?

Here is my use case: We are writing a data-agnostic machine learning framework [MLJ](https://github.com/alan-turing-institute/MLJ.jl). The user is to have the freedom to work with data in whatever format they want. The framework provides certain basic operations, for example standardization (whitening) of numeric features. If the user applies standardisation to his DataFrame, he will want a DataFrame as output. If he applies it to a JuliaDB table, then he should get a JuliaDB table in return. One-hot encoding is another example. And another: suppose the user wants to split his data into train and test sets. But the split data should be of the same data type.

**Comment by nalimilan** [comment]
DataFrames does implement `materializer`:
https://github.com/JuliaData/DataFrames.jl/blob/0b108a128fb94536d220f3f35ad5172259e6daca/src/other/tables.jl#L10

It makes little sense to me to look for a way to find out how to materialize a table for types which don't implement `materializer`: just fix these packages, as they don't implement the API correctly, period.

**Comment by ablaom** [comment]
Thanks for the help. After these comments and rereading the docs, I now understand how to work with Tables in my use case. Also just upgraded DataFrames to get the sensible materializer.

Feel free to close
