### ISSUE TITLE
Materialising matrix as a table

### ISSUE THREAD

**Issue by ablaom** [JuliaData/Tables.jl#59]
In our machine learning framework MLJ we have a function that materialises an abstract matrix (or named tuple of vectors corresponding to columns) as a table. Typical use case: a transformer takes a table as input, converts it to a matrix for processing, but then is expected to output a table once again. Perhaps such functionality should lie in Tables.jl? 

Here's our code at the moment:

````julia
"""
    MLJBase.table(cols; prototype=DataFrames)

Convert a named tuple of vectors `cols`, into a table. The table
type returned is the "preferred sink type" for `prototype` (see the
Tables.jl documentation), which is generally the type of `prototype`
itself, or a named tuple of vectors (in which case `cols` itself is
returned).

    MLJBase.table(X; names=nothing, prototype=DataFrames())

Convert an abstract matrix `X` into a table with `names` (a tuple of
symbols) as column names, or with labels `(:x1, :x2, ..., :xn)` where
`n=size(X, 2)`, if `names` is not specified.  Equivalent to `table(cols,
prototype=prototype)` where `cols` is the named tuple of columns of
`X`, with `keys(cols) = names`.

"""
function table(cols::NamedTuple; prototype=DataFrames.DataFrame())
    Tables.istable(prototype) || error("prototype is not tabular.")
    return Tables.materializer(prototype)(cols)
end
function table(X::AbstractMatrix; names=nothing, prototype=DataFrames.DataFrame())
    if names == nothing
        _names = tuple([Symbol(:x, j) for j in 1:size(X, 2)]...)
    else
        _names = names
    end
    cols = NamedTuple{_names}(tuple([X[:,j] for j in 1:size(X, 2)]...))
    return table(cols; prototype=prototype)
end
````  

Incidentally, we also provide convenience functions for selecting rows or columns from a table, returning a table of the "preferred sink type" of the input. Maybe such functionality should also live Tables.jl.

**Comment by quinnj** [comment]
The new `Tables.table` function has been added to wrap a matrix as a `MatrixTable`, which allows using `Tables.rows` and `Tables.columns` to access the underlying matrix data.
