### ISSUE TITLE
conflicting import of IteratorInterfaceExtensions 

### ISSUE THREAD

**Issue by hhaensel** [JuliaData/Tables.jl#70]
Compiling `Makie.jl` with `PackageCompiler` leads to a strange error message of `Tables.jl`, as reported
[here](https://discourse.julialang.org/t/ann-packagecompiler-with-incremental-system-images)

Comments by @davidanthoff lead me to removing `using IteratorInterfaceExtensions` in [line 5 of `Tables.jl`](https://github.com/JuliaData/Tables.jl/blob/master/src/Tables.jl#L5) as there is also a [`@require` statement in line 29](https://github.com/JuliaData/Tables.jl/blob/master/src/Tables.jl#L29)

After this modification `Tables.jl` is pre-compiling without error and PackageCompiler does not display any error.

Alternatively, if `IteratorInterfaceExtensions` is required elsewhere, the code in the require statement could be moved to the main part.

**Comment by nalimilan** [comment]
Let's try that then: https://github.com/JuliaData/Tables.jl/pull/71
