### ISSUE TITLE
Use `eachrow` and `eachcol` instead of `rows` and `columns`

### ISSUE THREAD

**Issue by Nosferican** [JuliaData/Tables.jl#78]
Would it make sense to use the methods already defined in the language rather than to add new functions that attempt to do the same?

**Comment by pdeffebach** [comment]
This would mean ensuring that across all packages, the iterators share some minimum set of behavior, which might be tough.

**Comment by Nosferican** [comment]
We already do that, every element is accessible through `propertynames`. The change is just to use `eachrow` instead of `Tables.rows`. For columns I believe it would be through `getindex` as `<:AbstractVector` (see #50 as an example for cols).

**Comment by pdeffebach** [comment]
I think the solution here is that the TableOperations interface that all Table types will be required to support should include an `eachrow` function. 

well, tbh I think there is a blurred line between the kind of streaming Tables.jl tries to support and more general `getindex` concept. But yeah I agree, this would be great to have.

**Comment by quinnj** [comment]
It would be a lot of churn for not much gain at this point. I'm also not sure we're really following the same `eachrow`/`eachcol` definitions provided in Base, so it would probably just muddy things. The interface is `Tables.rows` and `Tables.columns`, w/ the `Tables.` explicit qualification.

**Comment by nalimilan** [comment]
I kind of like that proposal. DataFrames uses `eachcol` currently, we chose that over `column` precisely because it matches the definition in Base. Moving to that terminology doesn't even have to be breaking: `const columns = eachcol` will ensure backwards compatibility, and we can keep the alias for a long time or even indefinitely.

Cc: @bkamins

**Comment by bkamins** [comment]
My initial comment:
> As @nalimilan the design in DataFrames.jl is to follow what Base does exactly. The only trick in `eachcol` is that you can have two options - one returning column name and the value and the other returning only values (the latter is currently the default in DataFrames.jl). The other good thing is that `eachcol` and `eachrow` live in Base now, so they can be used in any package we want and we will share the namespace (in particular - without having to load Tables.jl beforehand).

My afterthought:

> This will be problematic, because vector of named tuples is a table, so we would override the default behavior in Base. In other words: given the current design of Tables.jl we would commit a type piracy. This is not a problem in DataFrames.jl, but is a problem in Tables.jl.

**Comment by Nosferican** [comment]
Wouldn't we be defining `eachrow`/`eachcol` for `AbstractDataFrame`? That wouldn't be piracy as we own `AbstractDataFrame`.

**Comment by bkamins** [comment]
`eachrow` and `eachcol` are already defined for `AbstractDataFrame` and you can just use them. The problem is that `Tables.rows` and `Tables.columns` both accept `Any` argument (and that is why I guess @quinnj did want a separate namespace for these two functions to avoid type piracy).

**Comment by bkamins** [comment]
If the proposal is to have `eachcol` and `eachrow` defined in `Tables` namespace then it would not be a type piracy, but then the question is - as @quinnj asked - what is the benefit of writing `Tables.eachrow` over `Tables.rows` and `Tables.eachcol` over `Tables.columns`.

But if you find it more consistent then I guess it is not much harm to do what @nalimilan proposed, i.e. support both forms as they are not exported from Tables.jl anyway.

**Comment by nalimilan** [comment]
> This will be problematic, because vector of named tuples is a table, so we would override the default behavior in Base. In other words: given the current design of Tables.jl we would commit a type piracy. This is not a problem in DataFrames.jl, but is a problem in Tables.jl.

Good catch. So that's not possible.
