### ISSUE TITLE
Feature request: select with integer indices

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#79]
I find the `select(t, args...)` method extremely useful in various packages to take a few columns from any table like structure and then only select a few columns, but often I'd prefer to give the user the option to select column by number, so it be great to also allow numbers (rather than symbols) in args.

I find that this is not completely trivially implemented on the package side as for some table types one needs to start iterating to check the names (which if I understand correctly could cause problems on iterators that "consume" the input).

**Comment by Nosferican** [comment]
Could you go from `Integer` or `AbstractVector{<:Integer}` to `Symbol` or `AbstractVector{<:Symbol}` by doing something like `x = propertynames(table)[x]`? I believe the `propertynames` is efficient at this.

**Comment by piever** [comment]
There is no guarantee that `propertynames` returns the names of a table. It is true for say a `columntable` but the general case (iterator with potentially unknown scheme) can be trickier.

**Comment by Nosferican** [comment]
I thought we relied on `propertynames` in order to get the columns. Is it not even guaranteed with the `schema`? If so, maybe we do need an accessor for that, something à la `names`...
