### ISSUE TITLE
n-dimensional tables?

### ISSUE THREAD

**Issue by jandehaan** [JuliaData/Tables.jl#8]
Are there any plans to extend the interface to table-like structures with more than 2 dimensions?
Examples are 3-dimensional structures like Array{Any, 3} and Excel workbooks with multiple sheets.
An obvious extension might be
`Tables.sheets(table) => iterator with values accessible via getproperty(sheet, row, columnname)`
But how could this be extended to 4 dimensions or n-dimensions in general?

**Comment by rsokl** [comment]
You may want to draw inspiration from [xarray](http://xarray.pydata.org/en/stable/) if you are interested in n-dimensional tables.

**Comment by s-celles** [comment]
I discussed some months ago about it https://github.com/queryverse/IterableTables.jl/issues/65
