### ISSUE TITLE
Compilation times due to Requires

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaData/Tables.jl#82]
Requires seems like a real performance problem for using packages:
```Julia
# Right now, GeometryBasics depending on Tables + StructArrays
julia> @time using GeometryBasics
precompile: 8.338472 seconds
  2.824334 seconds (5.15 M allocations: 300.818 MiB, 3.89% gc time)

# With vchuravy perf fix for Requires https://github.com/MikeInnes/Requires.jl/pull/64
julia> @time using GeometryBasics
precompile: 8.332857 seconds
    2.779024 seconds (5.03 M allocations: 294.757 MiB, 3.77% gc time)

# With tables dropping Requires
julia> @time using GeometryBasics
precompile: 6.233432 seconds
  2.684032 seconds (4.91 M allocations: 288.117 MiB, 3.83% gc time)

# With StructArrays dropping Requires
julia> @time using GeometryBasics
precompile: 5.375375 seconds
  1.214614 seconds (2.42 M allocations: 168.382 MiB, 2.08% gc time)
```

Would it be possible to invert the dependency for DataValues, CategoricalArrays, WeakRefStrings? Especially if Tables doesn't increase the compile time as much anymore :P 

They sound like packages that could totally depend on a package like Tables - after all they're probably only used in a Table context anyways, no?

**Comment by SimonDanisch** [comment]
Relevant PRs/issues
https://github.com/MikeInnes/Requires.jl/pull/64
https://github.com/piever/StructArrays.jl/issues/64

**Comment by piever** [comment]
A brute force solution could also be a "type piracy" approach where placeholders for the relevant methods are put in a TablesBase package (which would have 3-4 lines) and overloaded from other packages. I mention it as type piracy as Tables should probably provide some fallbacks for those functions.

**Comment by quinnj** [comment]
Yeah, I'm beginning to think this is the best solution as well (I spent a good 3-4 hours yesterday digging into Requres.jl/loading.jl internals to see if there's any better solution there). We could also make that package generic beyond Tables, since people could use it for other packages if they wanted. We could call it SharedFunctions.jl or something; it would only allow empty generic function definitions, and would require/document a package as the "base" package or "manager" of the generic function. So in the case of `allocatecolumn`, Tables.jl would "own" it, meaning it alone is allowed to provide generic fallbacks.

**Comment by quinnj** [comment]
Ok, I spent a a good chunk yesterday discussing/exploring solutions and I think the best way forward would be to have a TablesAPI.jl package (started [here](https://github.com/JuliaData/TablesAPI.jl)), move the core api functions that need to be shared there, and then move the Requires.jl block definitions to the respective packages, having them take the super lightweight dependency of TablesAPI.jl. @nalimilan has already agreed on this course of action for CategoricalArrays, and I've reached out to @davidanthoff, so we'll just need to see what he says about taking the TablesAPI.jl dependency in DataValues.jl.

**Comment by SimonDanisch** [comment]
that sounds like a clean solution :)

**Comment by piever** [comment]
I also think that's a clean solution! May I vouch for including `refs` in TablesAPI? It's defined [here](https://github.com/piever/StructArrays.jl/blob/master/src/StructArrays.jl#L21) for WeakRefStrings and [here](https://github.com/piever/StructArrays.jl/blob/master/src/sort.jl#L3) for PooledArrays and gives the underlying references of a `StringArray` or `PooledArray` (see discussion at https://github.com/JuliaLang/julia/issues/31606): it basically gives some "cheaper array" where permuting elements there permutes element in the original array and things compare equal iff they compare equal in the original array.

**Comment by quinnj** [comment]
Ok, I've started work on https://github.com/JuliaData/DataAPI.jl as a data-related shared namespace where we can include some key functions that will help decouple several packages within the data ecosystem.
