### ISSUE TITLE
Why is there a dependency on TableTraits.jl?  

### ISSUE THREAD

**Issue by clarkevans** [JuliaData/Tables.jl#85]
I'm just curious.  Why is there a dependency on TableTraits?  I don't understand the relationship between these two packages.  I noticed the fallback for `istable` uses TableTraits. 

This was a question I always had, but, it was brought to the front of my mind upon seeing David's post with regard to the 0.1.20 tag: https://github.com/JuliaRegistries/General/pull/368#issuecomment-487407002

**Comment by quinnj** [comment]
Tables.jl opted for a dependency on TableTraits.jl to make it more convenient for users of Tables.jl to get access to *all* table types, and avoid the need to keep two separate implementations: one for Tables.jl and one for TableTraits.jl. By integrating directly in Tables.jl, packages can implement the Tables.jl interface and get automatic integration with TableTraits.jl and the rest of the Queryverse, basically for free.
