### ISSUE TITLE
DataValueRowIterator lies about shape

### ISSUE THREAD

**Issue by piever** [JuliaData/Tables.jl#96]
It seems like https://github.com/JuliaData/Tables.jl/issues/43 somehow resurfaced. When wrapping an iterator with `Base.HasShape`, the `DataValueRowIterator` claims `Base.HasShape` but has no `size` implementation (this causes some IndexedTables tests to fail). Maybe we should also forward `Base.size` to the wrapped iterator?

**Comment by quinnj** [comment]
Yeah, I suspect somebody isn't implementing the interface correctly though as the docs say that both `Base.length` and `Base.size` are required for `Base.HasShape`
![image](https://user-images.githubusercontent.com/2896623/58101498-0118df80-7b9d-11e9-8e67-98a9bc4666e2.png)

**Comment by quinnj** [comment]
@piever, can you check if current master fixes your case? (commit reference: https://github.com/JuliaData/Tables.jl/commit/77d456555c8daf162f6bc3de5f90c08626a2538c)

**Comment by piever** [comment]
Thanks! Yes, with Tables master tests pass locally. Could you tag a patch release?

**Comment by quinnj** [comment]
New release submitted
