### ISSUE TITLE
make allocatecolumn preserve levels of CategoricalValue

### ISSUE THREAD

**Issue by bkamins** [JuliaData/Tables.jl#99]
See https://github.com/JuliaData/DataFrames.jl/pull/1804#discussion_r288480065.

The problem is that if we use `allocatecolumn` on `CategoricalValue` we *forget* the original levels.

**Comment by nalimilan** [comment]
This requires adding a variant of `allocatecolumn` which takes a value rather than a type (which would fall back to calling `allocatecolumn` on the type).

**Comment by bkamins** [comment]
@nalimilan - I have thought a bit about it and I am not clear if what is proposed here is cleanly doable. The point is e.g. that passing value would disallow making a union with `Missing` (how would we express that)? Therefore I think that for now we have to live with what we have and just manually add levels after creating an categorical array if needed.
